Repository Team-Tiki/tiki-client, pull requests merged in 2024-09, with the labels that each got.

#225 [Docs] Storybook Build, Preview CI Script
  .github/workflows/chromatic.yml
  src/page/archiving/index/ArchivingPage.tsx
  src/story/common/Modal.stories.tsx
Labels: ⭐️주용, 📄Docs

#222 [Feat] Tabs 공통 컴포넌트 구현 및 적용
  src/common/component/Tab/TabButton.tsx
  src/common/component/Tab/TabList.tsx
  src/common/component/Tab/TabPanel.tsx
  src/common/component/Tab/Tabs.tsx
  src/common/component/Tab/index.tsx
  src/common/component/Tab/style.ts
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DocumentBar/DocumentBar.tsx
  src/page/archiving/index/component/DocumentItem/DocumentItem.style.ts
  src/page/archiving/index/component/DocumentItem/DocumentItem.tsx
  src/page/archiving/index/component/SelectedBlock/SelectedBlock.tsx
  src/page/archiving/index/component/TotalDocument/TotalDocument.tsx
  src/page/archiving/index/type/documentType.ts
  src/story/common/TabButton.stories.tsx
  src/story/common/Tabs.stories.tsx
  src/story/page/archiving/DocumentBar/DocumentItem.stories.tsx
Labels: ✨Feature, 🍭규홍

#220 [Feat] menu 공통컴포넌트 구현
  src/common/component/Menu/Menu.tsx
  src/common/component/Menu/MenuItem/MenuItem.style.ts
  src/common/component/Menu/MenuItem/MenuItem.tsx
  src/common/component/Menu/MenuList/MenuList.style.ts
  src/common/component/Menu/MenuList/MenuList.tsx
  src/page/archiving/index/ArchivingPage.tsx
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/SettingMenu/SettingMenu.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/SettingMenu/SettingMenu.tsx
  src/story/common/MenuList.stories.tsx
Labels: ✨Feature, 🤍보운
