Repository Team-Tiki/tiki-client, pull requests merged in 2024-10, with the labels that each got.

#228 [Feat] 비밀번호 재설정 QA
  src/common/component/Button/Button.tsx
  src/common/hook/useTimer.ts
  src/page/archiving/index/component/TimeBlockModal/component/Block/BlockModal.tsx
  src/page/archiving/index/component/TimeBlockModal/component/Upload/UploadModal.tsx
  src/page/login/password/auth/PasswordAuthPage.tsx
  src/page/login/password/reset/PasswordResetPage.tsx
  src/page/login/password/reset/hook/api/useResetPasswordMutation.ts
  src/page/login/password/reset/hook/common/usePasswordForm.ts
  src/page/signUp/info/component/InfoForm/InfoForm.tsx
  src/shared/component/Modal/ModalContainer.tsx
  src/shared/component/workSpaceModal/category/WorkSpaceCategory.tsx
  src/shared/component/workSpaceModal/complete/WorkSpaceComplete.tsx
  src/shared/component/workSpaceModal/image/WorkSpaceImage.tsx
  src/shared/component/workSpaceModal/index.tsx
  src/shared/component/workSpaceModal/info/WorkSpaceInfo.tsx
  src/shared/component/workSpaceModal/name/WorkSpaceName.tsx
  src/shared/util/validate.ts
  src/story/shared/modal/WorkSpaceCategory.stories.tsx
  src/story/shared/modal/WorkSpaceComplete.stories.tsx
  src/story/shared/modal/WorkSpaceImage.stories.tsx
  src/story/shared/modal/WorkSpaceInfo.stories.tsx
  src/story/shared/modal/WorkSpaceName.stories.tsx
Labels: 💫다은, ✨Feature, 🐛Bug

#211 [Refactor] 쇼케이스 페이지 리팩토링
  src/common/asset/svg/ic_arrow_left_white.svg
  src/common/asset/svg/ic_arrow_right_white.svg
  src/common/asset/svg/ic_default_profile.svg
  src/common/asset/svg/ic_logout.svg
  src/common/asset/svg/ic_password_reset.svg
  src/common/asset/svg/ic_setting.svg
  src/common/component/Carousel/Arrow.tsx
  src/page/showcase/index/ShowcasePage.tsx
  src/page/showcase/index/component/AdvBanner/AdvBanner.style.ts
  src/page/showcase/index/component/BannerSlider/BannerSlider.style.ts
  src/page/showcase/index/component/BannerSlider/BannerSlider.tsx
  src/page/showcase/index/component/ClubProfileCard/ClubProfileCard.style.ts
  src/page/showcase/index/component/ClubProfileCard/ClubProfileCard.tsx
  src/shared/component/LeftSidebar/LeftSidebar.style.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/story/common/Carousel.stories.tsx
Labels: ♻️Refactor, 🤍보운

#234 [Feat] refactor archiving page
  src/common/asset/svg/ic_accounting_circle.svg
  src/common/asset/svg/ic_add_btn.svg
  src/common/asset/svg/ic_arrow_left.svg
  src/common/asset/svg/ic_arrow_right.svg
  src/common/asset/svg/ic_calendar.svg
  src/common/asset/svg/ic_circle.svg
  src/common/asset/svg/ic_event_circle.svg
  src/common/asset/svg/ic_meeting_circle.svg
  src/common/asset/svg/ic_notice_circle.svg
  src/common/asset/svg/ic_study_circle.svg
  src/common/asset/svg/ic_task_circle.svg
  src/common/router/Router.tsx
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DaySection/DaySection.tsx
  src/page/archiving/index/component/TimeBlock/TimeBlock.style.ts
  src/page/archiving/index/component/TimeBlock/TimeBlock.tsx
  src/page/archiving/index/component/YearHeader/YearHeader.tsx
  src/page/archiving/index/constant/blockIcon.tsx
  src/page/archiving/index/hook/api/useGetTimeBlockQuery.ts
  src/page/archiving/index/hook/common/useDate.ts
  src/page/archiving/index/hook/common/useInteractTimeline.ts
Labels: ♻️Refactor, 💫다은

#240 [Feat] Divider 공통 컴포넌트 구현
  src/common/component/Divider/Divider.style.ts
  src/common/component/Divider/Divider.tsx
  src/story/common/Divider.stories.tsx
Labels: 💫다은, ✨Feature

#241 [Feat] DatePicker 컴포넌트 구현
  src/common/component/DatePicker/Calendar/Calendar.style.ts
  src/common/component/DatePicker/Calendar/Calendar.tsx
  src/common/component/DatePicker/Calendar/DatePickerCalendar.tsx
  src/common/component/DatePicker/Calendar/Dates/CalendarDates.tsx
  src/common/component/DatePicker/Calendar/Days/CalendarDays.tsx
  src/common/component/DatePicker/Calendar/Header/CalendarHeader.tsx
  src/common/component/DatePicker/DatePickerContainer/DatePickerContainer.style.ts
  src/common/component/DatePicker/DatePickerContainer/DatePickerContainer.tsx
  src/common/component/DatePicker/Trigger/DatePickerTrigger.tsx
  src/common/component/DatePicker/index.tsx
  src/common/hook/useCalendar.ts
  src/page/archiving/index/component/TimeBlockModal/component/Block/Date/BlockDate.tsx
  src/story/common/DatePicker.stories.tsx
  src/story/common/Select.stories.tsx
Labels: ✨Feature, 🍀채원

#245 [Feat] Tag 공통 컴포넌트 구현
  src/common/component/Input/Input.style.ts
  src/common/component/SupportingText/SupportingText.style.ts
  src/common/component/Tag/Tag.style.ts
  src/common/component/Tag/Tag.tsx
  src/common/style/theme/theme.ts
  src/page/signUp/info/component/InfoForm/InfoForm.style.ts
  src/story/common/Tag.stories.tsx
Labels: 💫다은, ✨Feature

#256 [Init] color, font 수정 사항 반영
  src/App.tsx
  src/common/component/Button/Button.style.ts
  src/common/component/DatePicker/Calendar/Calendar.style.ts
  src/common/component/Input/Input.style.ts
  src/common/component/Select/Select.style.ts
  src/common/component/Spinner/Spinner.tsx
  src/common/component/SupportingText/SupportingText.style.ts
  src/common/component/Tab/style.ts
  src/common/style/theme/theme.ts
  src/page/archiving/index/ArchivingPage.style.ts
  src/page/archiving/index/component/DaySection/DaySection.tsx
  src/page/archiving/index/component/MonthHeader/MonthHeader.style.ts
  src/page/archiving/index/component/TimeBlockModal/component/Block/Icon/BlockIcon.style.ts
  src/page/landing/component/Overview/Overview.style.ts
  src/page/login/password/auth/PasswordAuthPage.style.ts
  src/page/login/password/reset/PasswordResetPage.style.ts
  src/page/showcase/index/component/AdvBanner/AdvBanner.style.ts
  src/page/showcase/index/component/CategoryChip/CategoryChip.style.ts
  src/page/signUp/index/component/TermArea/TermArea.tsx
  src/page/signUp/index/component/TermsAgreeButton/TermsAgreeButton.style.ts
  src/page/signUp/info/InfoFormPage.style.ts
  src/page/signUp/info/component/InfoForm/InfoForm.style.ts
  src/shared/component/DeleteModal/DeleteModal.style.ts
  src/shared/component/LeftSidebar/LeftSidebar.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarMenuItem.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/PageIndicatorStick/PageIndicatorStick.style.ts
  src/shared/component/WorkSpaceModal/category/WorkSpaceCategory.style.ts
  src/shared/component/WorkSpaceModal/image/WorkSpaceImage.style.ts
  src/shared/component/WorkSpaceModal/name/WorkSpaceName.style.ts
  src/story/page/archiving/TimeBlock.stories.tsx
Labels: 💫다은, 🔗Init

#250 [Performance] Lottie-React Patch로 번들 사이즈 개선
  package.json
  patches/lottie-react@2.4.0.patch
  pnpm-lock.yaml
Labels: ⭐️주용, ✨Feature

#259 [Feat] 임시 SNB 구현
  .github/workflows/check.yml
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/shared/component/SideNavBar/TempSNB.tsx
  src/shared/component/SideNavBar/TempSnb.style.ts
Labels: ✨Feature, 🍭규홍

#243 [Feat] switch 공통 컴포넌트 구현
  src/common/asset/svg/ic_check.svg
  src/common/asset/svg/ic_grid.svg
  src/common/asset/svg/ic_list.svg
  src/common/asset/svg/ic_list_checked.svg
  src/common/asset/svg/icons.svg
  src/common/component/Switch/Switch.style.ts
  src/common/component/Switch/Switch.tsx
  src/story/common/Switch.stories.tsx
Labels: ✨Feature, 🤍보운

#260 [Performance] Font Subset 적용 및 Preload
  index.html
  public/font/subset-PretendardVariable.woff
  public/font/subset-PretendardVariable.woff2
  src/common/style/globalStyle.ts
  src/main.tsx
Labels: ⭐️주용, 💎Performance

#274 [Feat] 버튼 컴포넌트 Size 수정
  src/common/component/Button/Button.style.ts
  src/common/component/Button/Button.tsx
  src/common/component/CommandButton/CommandButton.tsx
  src/story/common/Button.stories.tsx
  src/story/common/CommandButton.stories.tsx
Labels: 💫다은, ✨Feature, 💄Design

#262 [Performance] chunk 분리 및 code splitting
  ic_check.svg
  package.json
  pnpm-lock.yaml
  src/common/router/Router.tsx
  src/common/router/lazy.ts
  stats.html
  vite.config.ts
Labels: 💫다은, 💎Performance

#279 [Feat] Checkbox 컴포넌트 퍼블리싱
  src/common/component/CheckBox/CheckBox.style.ts
  src/common/component/CheckBox/CheckBox.tsx
  src/story/common/CheckBox.stories.tsx
Labels: ⭐️주용, 💄Design

#273 [Feat] Header GUI 반영, 전체적인 레이아웃 구조 설계
  src/App.tsx
  src/common/asset/svg/ic_add_team.svg
  src/common/asset/svg/ic_alert_no.svg
  src/common/asset/svg/ic_alert_yes.svg
  src/common/asset/svg/ic_folder.svg
  src/common/asset/svg/ic_setting_gray.svg
  src/common/component/Menu/MenuList/MenuList.style.ts
  src/common/component/Text/Text.style.ts
  src/common/component/Text/Text.tsx
  src/common/style/theme/theme.ts
  src/page/archiving/index/ArchivingPage.style.ts
  src/page/archiving/index/component/DaySection/DaySection.style.ts
  src/page/archiving/index/component/DocumentBar/DocumentBar.style.ts
  src/page/archiving/index/component/DocumentBar/DocumentBar.tsx
  src/page/showcase/index/ShowcasePage.style.ts
  src/shared/component/Header/Header.style.ts
  src/shared/component/Header/Header.tsx
  src/story/shared/Header.stories.tsx
Labels: ⭐️주용, 💄Design

#270 [Fix] DatePicker 기능 추가 및 최종 GUI 적용
  src/common/asset/svg/ic_calendar_arrow_left.svg
  src/common/asset/svg/ic_calendar_arrow_right.svg
  src/common/component/DatePicker/Calendar/Calendar.style.ts
  src/common/component/DatePicker/Calendar/Calendar.tsx
  src/common/component/DatePicker/Calendar/DatePickerCalendar.tsx
  src/common/component/DatePicker/Calendar/Dates/CalendarDates.tsx
  src/common/component/DatePicker/Calendar/Dates/util/dateStyle.ts
  src/common/component/DatePicker/Calendar/Days/CalendarDays.tsx
  src/common/component/DatePicker/Calendar/Header/CalendarHeader.tsx
  src/common/component/DatePicker/DatePickerContainer/DatePickerContainer.tsx
  src/common/component/DatePicker/Trigger/DatePickerTrigger.style.ts
  src/common/component/DatePicker/Trigger/DatePickerTrigger.tsx
  src/common/component/DatePicker/index.style.ts
  src/common/component/DatePicker/index.tsx
  src/common/hook/useDatePicker.ts
  src/common/style/theme/theme.ts
  src/story/common/DatePicker.stories.tsx
Labels: ✨Feature, 🍀채원, 💄Design

#277 [Feat] input 공통 컴포넌트 GUI 반영 업데이트
  src/common/component/DatePicker/Trigger/DatePickerTrigger.tsx
  src/common/component/Input/Input.style.ts
  src/common/component/Input/Input.tsx
  src/common/component/SupportingText/SupportingText.style.ts
  src/page/archiving/index/component/DocumentBar/Total/Total.tsx
  src/page/archiving/index/component/TimeBlockModal/component/Block/BlockModal.tsx
  src/page/archiving/index/component/TimeBlockModal/component/Block/Date/BlockDate.tsx
  src/page/login/index/LoginPage.tsx
  src/page/login/password/auth/PasswordAuthPage.tsx
  src/page/login/password/reset/PasswordResetPage.tsx
  src/page/signUp/info/component/InfoForm/InfoForm.tsx
  src/page/signUp/info/component/PasswordForm/PasswordForm.tsx
  src/shared/component/WorkSpaceModal/name/WorkSpaceName.tsx
  src/story/common/Input.stories.tsx
  src/story/shared/ContentBox.stories.tsx
Labels: ✨Feature, 🤍보운

#289 [Refactor] Common 인풋과 Count Input 분리
  src/common/component/CountedInput/CountedInput.style.ts
  src/common/component/CountedInput/CountedInput.tsx
  src/common/component/Input/Input.style.ts
  src/common/component/Input/Input.tsx
  src/story/common/CountedInput.stories.tsx
  src/story/common/Input.stories.tsx
Labels: ⭐️주용, ♻️Refactor

#282 [Feat] 드라이브 페이지 File List 뷰 퍼블리싱
  src/common/component/Flex/Flex.style.ts
  src/common/component/Switch/Switch.style.ts
  src/common/component/Switch/Switch.tsx
  src/common/router/Router.tsx
  src/common/router/lazy.ts
  src/common/style/ellipsis.ts
  src/common/style/globalStyle.ts
  src/mock/data/drive.ts
  src/page/drive/.gitkeep
  src/page/drive/component/FileListHeader/FileListHeader.style.ts
  src/page/drive/component/FileListHeader/FileListHeader.tsx
  src/page/drive/component/FileListItem/FileListItem.style.ts
  src/page/drive/component/FileListItem/FileListItem.tsx
  src/page/drive/index.style.ts
  src/page/drive/index.tsx
  src/shared/component/ContentBox/ContentBox.style.ts
  src/shared/component/ContentBox/ContentBox.tsx
  src/shared/component/FileGrid/FileGrid.tsx
  src/shared/component/FileGrid/index.style.ts
  src/shared/component/Header/Header.style.ts
  src/shared/component/SideNavBar/LeftSidebar.tsx
  src/shared/constant/path.ts
  src/shared/type/file.ts
  src/story/common/Switch.stories.tsx
  src/story/page/drive/FileListHeader.stories.tsx
  src/story/page/drive/FileListItem.stories.tsx
  src/story/shared/FileGrid.stories.tsx
Labels: ⭐️주용, 💄Design

#285 [Feat] ToolTip 컴포넌트 구현
  src/common/asset/svg/ic_tooltip_arrow.svg
  src/common/component/ToolTip/ToolTip.style.ts
  src/common/component/ToolTip/ToolTip.tsx
  src/shared/component/SideNavBar/LeftSidebar.tsx
  src/shared/component/SideNavBar/LeftSidebarItem/LeftSidebarMenuItem.tsx
  src/story/common/ToolTip.stories.tsx
Labels: ✨Feature, 🍭규홍

#290 [Feat] 타임라인 GUI 수정사항 반영
  src/common/asset/svg/ic_accounting_circle.svg
  src/common/asset/svg/ic_arrow_back.svg
  src/common/asset/svg/ic_arrow_forward.svg
  src/common/asset/svg/ic_event.svg
  src/common/asset/svg/ic_meeting.svg
  src/common/asset/svg/ic_notice.svg
  src/common/asset/svg/ic_recruiting.svg
  src/common/asset/svg/ic_study.svg
  src/common/asset/svg/ic_task_circle.svg
  src/page/archiving/index/ArchivingPage.style.ts
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DaySection/DaySection.style.ts
  src/page/archiving/index/component/DaySection/DaySection.tsx
  src/page/archiving/index/component/DocumentBar/Selected/Selected.tsx
  src/page/archiving/index/component/MonthHeader/MonthHeader.style.ts
  src/page/archiving/index/component/MonthHeader/MonthHeader.tsx
  src/page/archiving/index/component/TimeBlock/TimeBlock.style.ts
  src/page/archiving/index/component/TimeBlockModal/component/Upload/UploadModal.tsx
  src/page/archiving/index/component/TimeLine/Day/Day.style.ts
  src/page/archiving/index/component/TimeLine/Day/Day.tsx
  src/page/archiving/index/component/TimeLine/TimeBlock/TimeBlock.style.ts
  src/page/archiving/index/component/TimeLine/TimeBlock/TimeBlock.tsx
  src/page/archiving/index/component/TimeLine/TimeLineHeader/TimeLineHeader.style.ts
  src/page/archiving/index/component/TimeLine/TimeLineHeader/TimeLineHeader.tsx
  src/page/archiving/index/component/TimeLine/index.tsx
  src/page/archiving/index/component/YearHeader/YearHeader.style.ts
  src/page/archiving/index/component/YearHeader/YearHeader.tsx
  src/page/archiving/index/constant/blockIcon.tsx
  src/page/archiving/index/constant/color.ts
  src/page/archiving/index/constant/icon.style.ts
  src/page/archiving/index/constant/icon.tsx
  src/page/archiving/index/constant/month.ts
  src/page/archiving/index/constant/timeBlock.ts
  src/page/archiving/index/hook/common/useDate.ts
  src/page/archiving/index/type/blockType.ts
  src/page/archiving/index/type/color.ts
  src/page/archiving/index/type/monthType.ts
  src/page/archiving/index/util/block.ts
  src/page/archiving/index/util/color.ts
  src/page/archiving/index/util/date.ts
  src/shared/component/ContentBox/ContentBox.tsx
  src/shared/hook/common/useBlockContext.tsx
  src/story/page/archiving/MonthHeader.stories.tsx
  src/story/page/archiving/TimeBlock.stories.tsx
  src/story/page/archiving/timeline/Day.stories.tsx
  src/story/page/archiving/timeline/TimeBlock.stories.tsx
Labels: 💫다은, ✨Feature

#297 [Feat] Global 드로어 컴포넌트 구현 및 스토어 생성
  src/App.tsx
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/hook/common/useInteractTimeline.ts
  src/shared/component/GlobalDrawer/GlobalDrawer.style.ts
  src/shared/component/GlobalDrawer/GlobalDrawer.tsx
  src/shared/store/drawer.ts
Labels: ⭐️주용, ✨Feature

#287 [Feat] menu 공통 컴포넌트 GUI 업데이트
  src/common/component/Menu/MenuItem/MenuItem.style.ts
  src/common/component/Menu/MenuItem/MenuItem.tsx
  src/common/component/Menu/MenuList/MenuList.style.ts
  src/common/component/Menu/MenuList/MenuList.tsx
  src/shared/component/SideNavBar/LeftSidebar.tsx
  src/story/common/MenuList.stories.tsx
Labels: ✨Feature, 🤍보운

#303 [Docs] 불필요한 스토리 삭제 + 일부 스토리 수정
  .github/workflows/automatic-aws-deployment.yml
  .github/workflows/chromatic.yml
  .github/workflows/storybook-deploy.yml
  .gitignore
  src/story/page/archiving/modal/BlockItem.stories.tsx
  src/story/page/archiving/modal/BlockModalTest.stories.tsx
  src/story/page/archiving/timeline/Day.stories.tsx
  src/story/page/archiving/timeline/TimeBlock.stories.tsx
  src/story/page/drive/FileListHeader.stories.tsx
  src/story/page/drive/FileListItem.stories.tsx
  src/story/page/landing/LandingPage.stories.tsx
  src/story/page/landing/Overview.stories.tsx
  src/story/page/login/LoginPage.stories.tsx
  src/story/page/showcase/AdvBanner.stories.tsx
  src/story/page/showcase/BannerSlider.stories.tsx
  src/story/page/showcase/CategoryChip.stories.tsx
  src/story/page/showcase/ClubProfileCard.stories.tsx
  src/story/page/signUp/InfoFormPage.stories.tsx
  src/story/page/signUp/TermArea.stories.tsx
  src/story/page/signUp/TermPage.stories.tsx
  src/story/page/signUp/TermsAgreeButton.stories.tsx
  src/story/shared/DeleteModal.stories.tsx
  src/story/shared/WorkSpaceModal.stories.tsx
Labels: ⭐️주용, 📄Docs

#305 [Deployment] Storybook GitHub pages 배포
  .github/workflows/storybook-deploy.yml
Labels: ⭐️주용, 🚀Deployment

#293 [Feat] SideNavBar 구현
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/common/asset/svg/ic_add.svg
  src/common/asset/svg/ic_avatar.svg
  src/common/asset/svg/ic_global.svg
  src/common/asset/svg/ic_tiki_logo.svg
  src/common/component/ToolTip/ToolTip.style.ts
  src/common/component/ToolTip/ToolTip.tsx
  src/common/style/theme/theme.ts
  src/shared/component/SideNavBar/Item/Item.style.ts
  src/shared/component/SideNavBar/Item/Item.tsx
  src/shared/component/SideNavBar/LeftSidebar.style.ts
  src/shared/component/SideNavBar/LeftSidebar.tsx
  src/shared/component/SideNavBar/LeftSidebarItem/LeftSidebarMenuItem.style.ts
  src/shared/component/SideNavBar/LeftSidebarItem/LeftSidebarMenuItem.tsx
  src/shared/component/SideNavBar/LeftSidebarItem/PageIndicatorStick/PageIndicatorStick.style.ts
  src/shared/component/SideNavBar/LeftSidebarItem/PageIndicatorStick/PageIndicatorStick.tsx
  src/shared/component/SideNavBar/SideNavBar.style.ts
  src/shared/component/SideNavBar/SideNavBar.tsx
  src/shared/constant/path.ts
  src/story/page/drive/FileListHeader.stories.tsx
  src/story/page/drive/FileListItem.stories.tsx
  src/story/shared/SideNavBar/Item.stories.tsx
Labels: ✨Feature, 🍭규홍
