Repository Team-Tiki/tiki-client, pull requests merged in 2024-11, with the labels that each got.

#309 [Fix] Content Box 스크롤 이슈 해결
  package.json
  pnpm-lock.yaml
  src/mock/data/drive.ts
  src/shared/component/ContentBox/ContentBox.style.ts
Labels: ⭐️주용, 🐛Bug

#300 [Feat] 인수인계 노트 작성 뷰 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/common/asset/svg/ic_delete_file.svg
  src/common/asset/svg/ic_file_round.svg
  src/common/component/Button/Button.style.ts
  src/common/component/Button/Button.tsx
  src/common/component/CommandButton/CommandButton.style.ts
  src/common/component/CommandButton/CommandButton.tsx
  src/common/component/DatePicker/Trigger/DatePickerTrigger.tsx
  src/common/component/Flex/Flex.style.ts
  src/common/component/RadioButton/RadioButton.style.ts
  src/common/component/RadioButton/RadioButton.tsx
  src/common/component/RadioButton/RadioGroup.tsx
  src/common/component/Tab/style.ts
  src/common/component/Tag/Tag.style.ts
  src/common/router/Router.tsx
  src/common/router/lazy.ts
  src/main.tsx
  src/page/archiving/index/component/DocumentBar/Selected/Selected.tsx
  src/page/archiving/index/component/TimeBlockModal/component/Upload/File/Add/BlockAdd.tsx
  src/page/handover/.gitkeep
  src/page/handover/note/NotePage.style.ts
  src/page/handover/note/NotePage.tsx
  src/page/handover/note/component/Custom/Custom.style.ts
  src/page/handover/note/component/Custom/Custom.tsx
  src/page/handover/note/component/File/File.style.ts
  src/page/handover/note/component/File/File.tsx
  src/page/handover/note/component/NoteDetail/NoteDetail.style.ts
  src/page/handover/note/component/NoteDetail/NoteDetail.tsx
  src/page/handover/note/component/Template/Template.style.ts
  src/page/handover/note/component/Template/Template.tsx
  src/page/handover/note/constants/template.ts
  src/page/handover/note/hooks/useFile.ts
  src/page/login/index/LoginPage.tsx
  src/shared/constant/form.ts
  src/shared/constant/path.ts
  src/story/common/Button.stories.tsx
  src/story/common/RadioGroup.stories.tsx
Labels: 💫다은, ✨Feature

#310 [Feat] Dashboard Page 퍼블리싱
  package.json
  src/common/asset/svg/ic_calendar_ver2.svg
  src/common/asset/svg/ic_note.svg
  src/common/router/Router.tsx
  src/page/archiving/index/ArchivingPage.tsx
  src/page/dashboard/DashboardPage.style.ts
  src/page/dashboard/DashboardPage.tsx
  src/page/dashboard/component/File/FileSection.tsx
  src/page/dashboard/component/Handover/HandoverSection.style.ts
  src/page/dashboard/component/Handover/HandoverSection.tsx
  src/page/dashboard/component/Handover/ListItem/ListItem.style.ts
  src/page/dashboard/component/Handover/ListItem/ListItem.tsx
  src/page/dashboard/component/Timeline/TimelineSection.style.ts
  src/page/dashboard/component/Timeline/TimelineSection.tsx
  src/page/dashboard/constant/notes.ts
  src/page/dashboard/type/listTag.ts
  src/page/dashboard/type/note.ts
  src/page/dashboard/util/alignTags.ts
  src/page/dashboard/util/color.ts
  src/shared/component/ContentBox/ContentBox.style.ts
  src/shared/component/ContentBox/ContentBox.tsx
  src/shared/component/FileGrid/FileGrid.tsx
  src/shared/component/FileGrid/FolderGrid.tsx
  src/shared/component/FileGrid/index.style.ts
  src/shared/type/content.ts
  src/story/page/dashboard/component/ListItem.stories.tsx
  src/story/shared/FileGrid.stories.tsx
  src/story/shared/FolderGrid.stories.tsx
Labels: ✨Feature, 🤍보운

#321 [Design] 비밀번호 재설정 뷰 GUI 반영
  package.json
  src/common/component/CountedInput/CountedInput.tsx
  src/common/component/Input/Input.tsx
  src/common/component/SupportingText/SupportingText.style.ts
  src/common/component/SupportingText/SupportingText.tsx
  src/page/login/password/auth/PasswordAuthPage.style.ts
  src/page/login/password/auth/PasswordAuthPage.tsx
  src/page/login/password/auth/hook/api/useResendMailMutation.ts
  src/page/login/password/auth/hook/common/useSupportingText.ts
  src/page/login/password/reset/PasswordResetPage.style.ts
  src/page/login/password/reset/PasswordResetPage.tsx
  src/page/login/password/reset/hook/common/usePasswordForm.ts
  src/page/login/password/type/supportingText.ts
  src/page/signUp/info/hook/api/useSendMailMutation.ts
  src/shared/api/email-verification/checking/index.ts
  src/shared/api/email-verification/password/index.ts
  src/shared/api/email-verification/signup/index.ts
  src/shared/constant/form.ts
  src/shared/hook/api/useVerifyCodeMutation.ts
Labels: 💫다은, ✨Feature, 💄Design

#317 [Feat] Login, Singup 페이지 GUI 반영
  src/common/asset/svg/logo_tiki_md.svg
  src/common/component/DatePicker/Calendar/Calendar.style.ts
  src/common/component/DatePicker/Trigger/DatePickerTrigger.tsx
  src/common/component/DatePicker/index.style.ts
  src/common/component/DatePicker/index.tsx
  src/common/component/Modal/Modal.style.ts
  src/common/component/SupportingText/SupportingText.style.ts
  src/common/router/Router.tsx
  src/common/router/lazy.ts
  src/page/login/index/LoginPage.style.ts
  src/page/login/index/LoginPage.tsx
  src/page/signUp/index/TermPage.tsx
  src/page/signUp/index/component/TermArea/TermArea.style.ts
  src/page/signUp/index/component/TermArea/TermArea.tsx
  src/page/signUp/index/component/TermItem/TermItem.style.ts
  src/page/signUp/index/component/TermItem/TermItem.tsx
  src/page/signUp/index/component/TermsAgreeButton/TermsAgreeButton.style.ts
  src/page/signUp/index/component/TermsAgreeButton/TermsAgreeButton.tsx
  src/page/signUp/index/hook/useTermForm.ts
  src/page/signUp/info/InfoFormPage.style.ts
  src/page/signUp/info/InfoFormPage.tsx
  src/page/signUp/info/UnivFormPage.tsx
  src/page/signUp/info/component/InfoForm/InfoForm.style.ts
  src/page/signUp/info/component/InfoForm/InfoForm.tsx
  src/page/signUp/info/component/PasswordForm/PasswordForm.tsx
  src/page/signUp/info/component/UnivSelectTriggerButton/Button.tsx
  src/page/signUp/info/hook/common/useInfoForm.ts
  src/page/signUp/info/hook/common/usePasswordForm.ts
  src/page/signUp/info/hook/common/useUnivForm.ts
  src/shared/constant/path.ts
  src/story/common/DatePicker.stories.tsx
Labels: ⭐️주용, ✨Feature

#319 [Feat] 휴지통 뷰 퍼블리싱
  src/common/component/Select/Select.tsx
  src/common/hook/useMultiSelect.ts
  src/common/router/Router.tsx
  src/common/router/lazy.ts
  src/common/style/scroll.ts
  src/page/deleted/.gitkeep
  src/page/deleted/index.tsx
  src/page/drive/index.style.ts
  src/page/drive/index.tsx
  src/shared/component/ContentBox/ContentBox.style.ts
  src/shared/component/EmptySection/EmptySection.style.ts
  src/shared/component/EmptySection/EmptySection.tsx
  src/shared/component/EmptySection/constant.ts
  src/shared/component/FileGrid/FileGrid.tsx
  src/shared/component/FileGrid/index.style.ts
  src/shared/constant/path.ts
Labels: ⭐️주용, ✨Feature

#326 [Feat] 대시보드 페이지 timeline date issue 및 css 수정
  src/page/dashboard/DashboardPage.tsx
  src/page/dashboard/component/Handover/ListItem/ListItem.style.ts
  src/page/dashboard/component/Handover/ListItem/ListItem.tsx
  src/page/dashboard/component/Timeline/Timeline/Timeline.style.ts
  src/page/dashboard/component/Timeline/Timeline/Timeline.tsx
  src/page/dashboard/component/Timeline/index.tsx
  src/page/dashboard/constant/notes.ts
  src/page/dashboard/util/alignTags.ts
Labels: ✨Feature, 🤍보운

#322 [Feat] teamId 전역 상태로 구현
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/DateProvider.tsx
  src/page/archiving/index/component/DocumentBar/Item/Item.tsx
  src/page/archiving/index/component/DocumentBar/Selected/Selected.tsx
  src/page/archiving/index/component/DocumentBar/Total/Total.tsx
  src/page/archiving/index/component/TimeBlockModal/component/Upload/UploadModal.tsx
  src/page/archiving/index/component/TimeLine/Day/Day.style.ts
  src/page/archiving/index/component/TimeLine/TimeLineHeader/TimeLineHeader.style.ts
  src/page/archiving/index/component/TimeLine/index.tsx
  src/page/archiving/index/hook/common/useDate.ts
  src/page/dashboard/.gitkeep
  src/page/dashboard/component/Timeline/Timeline/Timeline.tsx
  src/page/dashboard/component/Timeline/index.tsx
  src/shared/api/members/teams/index.ts
  src/shared/component/SideNavBar/SideNavBar.tsx
  src/shared/hook/common/useInitializeTeamId.tsx
  src/shared/store/team.ts
Labels: ♻️Refactor, 💫다은, ✨Feature

#329 [Feat] 인수인계 노트 페이지 수정
  src/common/asset/svg/ic_plus_button.svg
  src/common/component/CommandButton/CommandButton.style.ts
  src/common/component/RadioButton/RadioButton.style.ts
  src/common/component/RadioButton/RadioButton.tsx
  src/common/component/RadioButton/RadioGroup.tsx
  src/page/handover/note/component/Custom/Custom.style.ts
  src/page/handover/note/component/NoteDetail/NoteDetail.style.ts
  src/page/handover/note/component/NoteDetail/NoteDetail.tsx
  src/page/handover/note/component/Template/Template.style.ts
  src/page/handover/note/constants/tag.ts
  src/page/landing/LandingPage.tsx
  src/page/login/index/hook/useLoginMutation.ts
  src/shared/component/RouteNav/RouteNav.tsx
  src/shared/component/SideNavBar/SideNavBar.tsx
Labels: 💫다은, ✨Feature, 💄Design

#323 [Feat] 인수인계 노트 페이지 퍼블리싱
  src/common/asset/svg/ic_more.svg
  src/common/asset/svg/ic_sticky_note_2.svg
  src/common/component/Select/Select.style.ts
  src/common/hook/useMultiSelect.ts
  src/common/router/Router.tsx
  src/page/deleted/index.tsx
  src/page/handover/HandoverPage.style.ts
  src/page/handover/HandoverPage.tsx
  src/page/handover/component/NoteItem/NoteItem.style.ts
  src/page/handover/component/NoteItem/NoteItem.tsx
  src/page/handover/component/NoteListHeader/NoteListHeader.style.ts
  src/page/handover/component/NoteListHeader/NoteListHeader.tsx
  src/page/handover/constant/noteList.ts
  src/story/page/handover/NoteItem.stories.tsx
Labels: ✨Feature, 🍭규홍
