Repository Team-Tiki/tiki-client, pull requests merged in 2024-12, with the labels that each got.

#336 [Feat] OAS Generator 도입
  .gitignore
  apps/client/.eslintignore
  apps/client/package.json
  apps/client/src/shared/__generated__/schema.d.ts
  apps/client/src/shared/api/client.ts
  apps/client/src/shared/api/middleware.ts
  apps/client/src/shared/hook/common/useInitializeTeamId.tsx
  pnpm-lock.yaml
Labels: 🫧다은, ✨Feature, 🔗Init

#340 [Fix] 모노레포 적용 후 스토리북에서 발생하는 에러 해결
  apps/client/.storybook/main.ts
  apps/client/.storybook/preview-body.html
  apps/client/.storybook/preview.tsx
  apps/client/src/page/archiving/index/component/TimeBlockModal/component/Upload/UploadModal.tsx
  apps/client/src/page/login/index/hook/useLoginMutation.ts
  apps/client/src/page/login/password/auth/hook/api/useResendMailMutation.ts
  apps/client/src/page/login/password/reset/hook/api/useResetPasswordMutation.ts
  apps/client/src/page/signUp/info/hook/api/useSendMailMutation.ts
  apps/client/src/page/signUp/info/hook/api/useSignupMutation.ts
  apps/client/src/shared/hook/api/useVerifyCodeMutation.ts
  apps/client/src/shared/hook/common/useTokenError.ts
  apps/client/src/story/common/Select.stories.tsx
  apps/client/src/story/common/Toast.stories.tsx
  apps/client/src/story/page/dashboard/component/ListItem.stories.tsx
  packages/ui/src/CommandButton/CommandButton.tsx
  packages/ui/src/Tab/style.ts
  packages/ui/src/Toast/index.ts
  packages/ui/src/Toast/store.ts
  packages/ui/src/ToastContainer/ToastProvider.tsx
  packages/ui/src/index.ts
  packages/utils/src/index.ts
  packages/utils/src/store/index.ts
  pnpm-lock.yaml
Labels: ⭐️주용, 🐛Bug

#339 [Fix] 아카이빙 페이지 api path 수정
  apps/client/src/page/archiving/index/ArchivingPage.tsx
  apps/client/src/page/archiving/index/component/TimeLine/TimeBlock/TimeBlock.style.ts
  apps/client/src/page/archiving/index/component/TimeLine/TimeBlock/TimeBlock.tsx
  apps/client/src/page/archiving/index/component/TimeLine/index.tsx
  apps/client/src/page/archiving/index/hook/common/useInteractTimeline.ts
  apps/client/src/page/archiving/index/type/blockType.ts
  apps/client/src/page/archiving/index/util/block.ts
  apps/client/src/page/dashboard/component/Timeline/Timeline/Timeline.tsx
  apps/client/src/shared/__generated__/schema.d.ts
Labels: 🫧다은, 🐛Bug

#343 [Feat] 드라이브 페이지 폴더/파일 조회 API 연걸
  apps/client/package.json
  apps/client/src/page/drive/component/FileListHeader/FileListHeader.tsx
  apps/client/src/page/drive/component/FileListItem/FileListItem.tsx
  apps/client/src/page/drive/component/FileListItem/FolderListItem.tsx
  apps/client/src/page/drive/hook/api/queries.ts
  apps/client/src/page/drive/hook/common/useSelectDocuments.ts
  apps/client/src/page/drive/index.tsx
  apps/client/src/page/drive/type.ts
  apps/client/src/shared/__generated__/schema.d.ts
  apps/client/src/shared/api/client.ts
  apps/client/src/shared/api/time-blocks/team/timeline/index.ts
  apps/client/src/shared/component/FileGrid/FileGrid.tsx
  apps/client/src/shared/component/FileGrid/FolderGrid.tsx
  apps/client/src/shared/component/FileGrid/icon.tsx
  apps/client/src/shared/type/file.ts
  apps/client/src/shared/util/date.ts
  packages/utils/src/hooks/useMultiSelect.ts
Labels: ⭐️주용, ✨Feature

#353 [Fix] Client 패키지 File 타입 관련 에러 해결
  apps/client/src/mock/data/drive.ts
  apps/client/src/page/archiving/index/component/TimeLine/index.tsx
  apps/client/src/page/dashboard/component/File/FileSection.tsx
  apps/client/src/page/dashboard/component/Timeline/Timeline/Timeline.tsx
  apps/client/src/page/deleted/index.tsx
  apps/client/src/page/drive/component/FileListItem/FileListItem.tsx
  apps/client/src/story/page/drive/FileListItem.stories.tsx
  apps/client/src/story/shared/FileGrid.stories.tsx
  apps/client/src/story/shared/FolderGrid.stories.tsx
Labels: ⭐️주용, 🐛Bug

#354 [Feat] workspace setting view 구현
  apps/client/src/common/router/Router.tsx
  apps/client/src/page/workspaceSetting/component/InfoSetting.tsx
  apps/client/src/page/workspaceSetting/component/ProfileSetting.tsx
  apps/client/src/page/workspaceSetting/component/styles.ts
  apps/client/src/page/workspaceSetting/constant/index.ts
  apps/client/src/page/workspaceSetting/index.tsx
  apps/client/src/page/workspaceSetting/styles.ts
  apps/client/src/shared/component/Header/Header.tsx
  apps/client/src/shared/constant/form.ts
  apps/client/src/shared/constant/path.ts
  apps/client/src/shared/util/validate.ts
  apps/client/src/story/common/Select.stories.tsx
  packages/icon/tsconfig.json
  packages/ui/src/CommandButton/CommandButton.tsx
  packages/ui/src/Select/Select.style.ts
  packages/ui/src/Select/Select.tsx
  packages/ui/tsconfig.json
  packages/utils/tsconfig.json
Labels: ✨Feature, 🍭규홍

#362 [Fix] Team Id 초기화 오류 해결
  apps/client/src/page/dashboard/component/Timeline/Timeline/Timeline.tsx
  apps/client/src/shared/hook/common/useInitializeTeamId.tsx
Labels: 🫧다은, 🐛Bug, 💥Hotfix

#347 [Feat] 휴지통 파일 Get api 연결
  apps/client/src/page/deleted/index.tsx
  apps/client/src/shared/__generated__/schema.d.ts
  apps/client/src/shared/component/FileGrid/FileGrid.tsx
Labels: 🫧다은, ✨Feature
