Repository Team-Tiki/tiki-client, pull requests merged in 2024-07, with the labels that each got.

#4 [Init] emotion초기세팅
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/common/style/globalStyle.ts
  src/common/style/theme/emotion.d.ts
  src/common/style/theme/theme.ts
  tsconfig.json
  vite.config.ts
Labels: 🍭규홍, 🔗Init

#3 [Init] eslint, prettier, 절대경로 initial setting
  .eslintrc.cjs
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/main.tsx
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 🍀채원, 🤍보운, 🔗Init

#6 [Feat] MSW, Storybook 초기세팅 완료
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/feature-request.md
  .gitignore
  .prettierrc
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/App.tsx
  src/common/component/Button/Button.tsx
  src/common/style/globalStyle.ts
  src/common/style/theme/emotion.d.ts
  src/common/style/theme/theme.ts
  src/main.tsx
  src/mock/browser.ts
  src/mock/data/showCase.ts
  src/mock/handler/index.ts
  src/mock/handler/showCase.ts
  src/story/Button.stories.tsx
  tsconfig.json
Labels: ⭐️주용, ✨Feature

#9 [feat] 스타일 가이드 세팅
  .storybook/preview-head.html
  .storybook/preview.tsx
  index.html
  package.json
  src/common/style/globalStyle.ts
  src/common/style/theme/emotion.d.ts
  src/common/style/theme/theme.ts
  tsconfig.json
Labels: 💫다은, ✨Feature

#11 [Init] svgr 세팅하기
  package.json
  pnpm-lock.yaml
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.json
  vite.config.ts
Labels: 🤍보운, 🔗Init

#20 [feat] 공통 Heading 컴포넌트 구현
  src/common/component/Heading/Heading.tsx
  src/common/component/Heading/heading.style.ts
  src/story/Heading.stories.tsx
Labels: ✨Feature, 🍭규홍

#23 [Feat] Select, Dropdown, Label 컴포넌트 구현
  index.html
  src/common/asset/arrow-down.svg
  src/common/component/Button/Button.style.ts
  src/common/component/Button/Button.tsx
  src/common/component/Dropdown/Dropdown.style.ts
  src/common/component/Dropdown/Dropdown.tsx
  src/common/component/Dropdown/DropdownItem.tsx
  src/common/component/Dropdown/DropdownList.tsx
  src/common/component/Dropdown/DropdownTrigger.tsx
  src/common/component/Dropdown/index.tsx
  src/common/component/Label/Label.style.ts
  src/common/component/Label/Label.tsx
  src/common/component/Select/Select.style.ts
  src/common/component/Select/Select.tsx
  src/common/hook/index.ts
  src/common/hook/useOutsideClick.ts
  src/common/hook/useOverlay.ts
  src/common/style/theme/emotion.d.ts
  src/common/style/theme/theme.ts
  src/story/common/Button.stories.tsx
  src/story/common/Label.stories.tsx
  src/story/common/Select.stories.tsx
  tsconfig.json
  vite.config.ts
Labels: ⭐️주용, ✨Feature

#26 [Feat] input 공통 컴포넌트 구현
  src/common/component/Input/Input.style.ts
  src/common/component/Input/Input.tsx
  src/story/common/Input.stories.tsx
  svg.d.ts
  tsconfig.json
  vite.config.ts
Labels: ✨Feature, 🤍보운

#21 [Feat] 모달 공통 컴포넌트
  src/common/component/Modal/Modal.style.ts
  src/common/component/Modal/Modal.tsx
  src/common/hook/Modal/useModal.tsx
  src/common/hook/usePreventGoBack.tsx
  src/story/common/Modal.stories.tsx
Labels: ✨Feature, 🍀채원

#31 [Refactor] Select 컴포넌트 GUI에 따른 hover color, scroll 적용
  src/common/component/Select/Select.style.ts
  src/story/common/Select.stories.tsx
Labels: ⭐️주용, ♻️Refactor

#24 [Feat] 텍스트 공통 컴포넌트 제작
  src/common/component/Text/Text.style.ts
  src/common/component/Text/Text.tsx
  src/common/type/design.ts
  src/story/Text.stories.tsx
Labels: 💫다은, ✨Feature

#27 [Feat] 공통 헤더 구현
  src/common/asset/svg/index.tsx
  src/common/asset/svg/logo_tiki_md.svg
  src/common/asset/svg/logo_tiki_sm.svg
  src/common/component/Header/Header.style.ts
  src/common/component/Header/Header.tsx
  src/common/component/Heading/Heading.tsx
Labels: ✨Feature, 🍭규홍

#28 [Feat] 아카이빙 페이지 달 헤더 구현
  src/common/style/theme/emotion.d.ts
  src/common/style/theme/theme.ts
  src/page/Archiving/component/MonthHeader.style.ts
  src/page/Archiving/component/MonthHeader.tsx
  src/page/Archiving/constant/date.ts
  src/story/page/MonthHeader.stories.tsx
Labels: 💫다은, ✨Feature

#36 [Feat] 타임라인 body section 구현
  src/page/Archiving/component/DaySection.style.ts
  src/page/Archiving/component/DaySection.tsx
  src/page/archiving/component/DaySection.style.ts
  src/page/archiving/component/DaySection.tsx
  src/page/archiving/component/MonthHeader.style.ts
  src/page/archiving/component/MonthHeader.tsx
  src/page/archiving/constant/date.ts
  src/story/common/Heading.stories.tsx
  src/story/common/Text.stories.tsx
  src/story/page/archiving/DaySection.stories.tsx
  src/story/page/archiving/MonthHeader.stories.tsx
Labels: 💫다은, ✨Feature

#40 [Feat] 스토리북 배포 및 CD 구축
  .github/workflows/chromatic.yml
  package.json
  pnpm-lock.yaml
  src/common/hook/index.ts
  src/common/hook/useModal.tsx
  src/common/hook/usePreventGoBack.tsx
  src/page/landing/LandingPage.tsx
  src/page/landing/component/FeatureSection/FeatureSection.style.ts
  src/page/landing/component/FeatureSection/FeatureSection.tsx
  src/story/common/Header.stories.tsx
  src/story/common/Modal.stories.tsx
  src/story/common/Select.stories.tsx
  src/story/page/archiving/MonthHeader.stories.tsx
  src/story/page/landing/LandingFeatureSection.stories.tsx
Labels: ⭐️주용, 📄Docs, ♻️Refactor

#44 [Fix] 폴더명 대문자 이슈 해결
  src/page/Archiving/component/DaySection.style.ts
  src/page/Archiving/component/DaySection.tsx
  src/page/Archiving/component/MonthHeader.style.ts
  src/page/Archiving/component/MonthHeader.tsx
  src/page/Archiving/constant/date.ts
Labels: 💫다은, 🐛Bug

#43 #38 docs: 크로마틱 ci 스크립트 수정
  .github/workflows/chromatic.yml
  .gitignore
  src/common/component/Header/Header.style.ts
  src/common/component/Header/Header.tsx
  src/story/common/Header.stories.tsx
Labels: ⭐️주용, 📄Docs

#41 [Feat] input supportingText 구현
  src/common/component/Input/Input.style.ts
  src/common/component/Input/Input.tsx
  src/common/component/SupportingText/SupportingText.style.ts
  src/common/component/SupportingText/SupportingText.tsx
  src/story/common/Input.stories.tsx
Labels: ✨Feature, 🤍보운

#48 #46 feat: router 설계
  src/common/router/Router.tsx
  src/main.tsx
Labels: ⭐️주용, ✨Feature

#52 [Feat] 쇼케이스 페이지 club profile card 구현
  src/common/asset/svg/default_profile.svg
  src/common/type/design.ts
  src/page/showcase/component/ClubProfileCard/ClubProfileCard.style.ts
  src/page/showcase/component/ClubProfileCard/ClubProfileCard.tsx
  src/story/page/archiving/DaySection.stories.tsx
  src/story/page/showcase/ClubProfileCard.stories.tsx
Labels: ✨Feature, 🤍보운

#54 [Feat] 회원가입 이용약관 동의 페이지 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/common/asset/svg/check.svg
  src/common/asset/svg/check_active.svg
  src/common/component/Button/Button.style.ts
  src/common/component/Flex/Flex.style.ts
  src/common/component/Flex/Flex.tsx
  src/common/component/Header/Header.style.ts
  src/common/component/Header/Header.tsx
  src/common/router/Router.tsx
  src/page/signIn/index/TermPage.style.ts
  src/page/signIn/index/TermPage.tsx
  src/page/signIn/index/component/TermArea/TermArea.style.ts
  src/page/signIn/index/component/TermArea/TermArea.tsx
  src/page/signIn/index/component/TermsAgreeButton/TermsAgreeButton.style.ts
  src/page/signIn/index/component/TermsAgreeButton/TermsAgreeButton.tsx
  src/page/signIn/info/InfoFormPage.tsx
  src/shared/store/auth.ts
  src/story/common/Flex.stories.tsx
  src/story/common/Header.stories.tsx
  src/story/page/signIn/TermArea.stories.tsx
  src/story/page/signIn/TermPage.stories.tsx
  src/story/page/signIn/TermsAgreeButton.stories.tsx
Labels: ⭐️주용, ♻️Refactor, 💄Design

#55 [Feat] 달에 따른 일수 렌더링
  package.json
  pnpm-lock.yaml
  src/common/router/Router.tsx
  src/page/archiving/Archiving.style.ts
  src/page/archiving/ArchivingPage.tsx
  src/page/archiving/component/DaySection/DaySection.style.ts
  src/page/archiving/component/DaySection/DaySection.tsx
  src/page/archiving/component/MonthHeader/MonthHeader.style.ts
  src/page/archiving/component/MonthHeader/MonthHeader.tsx
  src/page/archiving/type/monthType.ts
  src/page/archiving/util/getMonthDate.ts
  src/story/page/archiving/DaySection.stories.tsx
Labels: 💫다은, ✨Feature

#60 [Feat] showcase 페이지 category chip 구현
  src/page/showcase/component/CategoryChip/CategoryChip.style.ts
  src/page/showcase/component/CategoryChip/CategoryChip.tsx
  src/page/showcase/constant/category.ts
  src/story/page/showcase/CategoryChip.stories.tsx
  src/story/page/showcase/ClubProfileCard.stories.tsx
Labels: ✨Feature, 🤍보운

#63 [Feat] 타임라인 헤더 구현 & 블록 생성 버튼
  src/common/asset/svg/arrow_left.svg
  src/common/asset/svg/arrow_right.svg
  src/common/asset/svg/calendar.svg
  src/page/archiving/Archiving.style.ts
  src/page/archiving/ArchivingPage.style.ts
  src/page/archiving/ArchivingPage.tsx
  src/page/archiving/util/getMonthDate.ts
Labels: 💫다은, ✨Feature

#65 [Feat] 회원가입 개인정보입력 퍼블리싱
  src/common/asset/svg/arrow-down.svg
  src/common/component/Button/Button.style.ts
  src/common/component/Input/Input.style.ts
  src/common/component/Select/Select.tsx
  src/common/router/Router.tsx
  src/common/style/theme/theme.ts
  src/page/signIn/index/TermPage.style.ts
  src/page/signIn/index/TermPage.tsx
  src/page/signIn/index/component/TermArea/TermArea.tsx
  src/page/signIn/index/component/TermsAgreeButton/TermsAgreeButton.style.ts
  src/page/signIn/info/InfoFormPage.style.ts
  src/page/signIn/info/InfoFormPage.tsx
  src/page/signIn/info/constant/index.ts
  src/story/common/Select.stories.tsx
  src/story/page/signIn/InfoFormPage.stories.tsx
Labels: ⭐️주용, ✨Feature, 💄Design

#68 [Feat] 로그인 페이지 퍼블리싱
  src/common/router/Router.tsx
  src/page/login/LoginPage.style.ts
  src/page/login/LoginPage.tsx
  src/story/page/login/LoginPage.stories.tsx
Labels: ⭐️주용, 💄Design

#71 [Refactor] 컴포넌트 스토리 문서화 재정립
  src/common/component/Select/Select.style.ts
  src/common/component/Text/Text.tsx
  src/common/style/theme/theme.ts
  src/common/type/design.ts
  src/shared/component/createWorkSpace/category/WorkSpaceCategory.tsx
  src/story/common/Button.stories.tsx
  src/story/common/Header.stories.tsx
  src/story/common/Heading.stories.tsx
  src/story/common/Input.stories.tsx
  src/story/common/Text.stories.tsx
  src/story/page/archiving/DaySection.stories.tsx
Labels: ⭐️주용, 📄Docs, ♻️Refactor

#72 [Feat] showcase페이지 adv banner 구현
  src/common/style/theme/theme.ts
  src/page/showcase/component/AdvBanner/AdvBanner.style.ts
  src/page/showcase/component/AdvBanner/AdvBanner.tsx
  src/story/page/showcase/AdvBanner.stories.tsx
Labels: ✨Feature, 🤍보운

#75 [Feat] 타임 블록 타임라인에 배치시키기
  src/common/asset/svg/add_btn.svg
  src/common/asset/svg/circle.svg
  src/common/asset/svg/dotted_line.svg
  src/common/asset/svg/eclipse.svg
  src/common/component/Flex/Flex.style.ts
  src/common/component/Header/Header.style.ts
  src/common/component/Input/Input.style.ts
  src/common/style/theme/theme.ts
  src/page/archiving/ArchivingPage.style.ts
  src/page/archiving/ArchivingPage.tsx
  src/page/archiving/component/DaySection/DaySection.style.ts
  src/page/archiving/component/DaySection/DaySection.tsx
  src/page/archiving/component/MonthHeader/MonthHeader.style.ts
  src/page/archiving/component/TimeBlock/TimeBlock.style.ts
  src/page/archiving/component/TimeBlock/TimeBlock.tsx
  src/page/archiving/constant/color.ts
  src/page/archiving/constant/timeBlock.ts
  src/page/archiving/util/alignBlocks.ts
  src/page/archiving/util/getRandomColor.ts
  src/story/page/archiving/TimeBlock.stories.tsx
Labels: 💫다은, ✨Feature

#78 [Feat] 블록생성 모달
  src/common/asset/svg/file-delete.svg
  src/common/asset/svg/icon-book.svg
  src/common/asset/svg/icon-laptop.svg
  src/common/asset/svg/icon-money.svg
  src/common/asset/svg/icon-party.svg
  src/common/asset/svg/icon-people.svg
  src/common/asset/svg/icon-speaker.svg
  src/common/asset/svg/plus-gray.svg
  src/common/component/Modal/Modal.style.ts
  src/common/component/SupportingText/SupportingText.tsx
  src/common/hook/useModal.tsx
  src/page/archiving/component/Modal/Block/BlockModal.style.ts
  src/page/archiving/component/Modal/Block/BlockModal.tsx
  src/page/archiving/component/Modal/Block/Date/BlockDate.style.ts
  src/page/archiving/component/Modal/Block/Date/BlockDate.tsx
  src/page/archiving/component/Modal/Block/Icon/BlockIcon.style.ts
  src/page/archiving/component/Modal/Block/Icon/BlockIcon.tsx
  src/page/archiving/component/Modal/Box/BlockBox.style.ts
  src/page/archiving/component/Modal/Box/BlockBox.tsx
  src/page/archiving/component/Modal/Upload/File/Add/BlockAdd.style.ts
  src/page/archiving/component/Modal/Upload/File/Add/BlockAdd.tsx
  src/page/archiving/component/Modal/Upload/File/List/BlockItem.style.ts
  src/page/archiving/component/Modal/Upload/File/List/BlockItem.tsx
  src/page/archiving/component/Modal/Upload/UploadModal.style.ts
  src/page/archiving/component/Modal/Upload/UploadModal.tsx
  src/page/archiving/constant/error.ts
  src/page/archiving/constant/icon.ts
  src/page/archiving/hook/useDateRange.tsx
  src/page/archiving/hook/useFile.tsx
  src/page/archiving/util/dateUtils.ts
  src/shared/component/createWorkSpace/info/WorkSpaceInfo.style.ts
  src/shared/component/createWorkSpace/info/WorkSpaceInfo.tsx
  src/shared/component/createWorkSpace/name/WorkSpaceName.style.ts
  src/shared/constant/index.ts
  src/story/common/Modal.stories.tsx
  src/story/page/archiving/modal/BlockAdd.stories.tsx
  src/story/page/archiving/modal/BlockIcon.stories.tsx
  src/story/page/archiving/modal/BlockItem.stories.tsx
  src/story/page/archiving/modal/BlockModal.stories.tsx
  src/story/page/archiving/modal/BlockModalTest.stories.tsx
  src/story/shared/modal/WorkSpaceCategory.stories.tsx
  src/story/shared/modal/WorkSpaceComplete.stories.tsx
  src/story/shared/modal/WorkSpaceImage.stories.tsx
  src/story/shared/modal/WorkSpaceInfo.stories.tsx
  src/story/shared/modal/WorkSpaceName.stories.tsx
Labels: ✨Feature, 🍀채원

#80 [Feat] 삭제 모달 구현
  src/common/asset/svg/workspace-complete.svg
  src/common/component/Button/Button.style.ts
  src/common/component/Modal/Modal.style.ts
  src/common/style/theme/theme.ts
  src/shared/component/DeleteModal/DeleteModal.style.ts
  src/shared/component/DeleteModal/DeleteModal.tsx
  src/shared/component/createWorkSpace/complete/WorkSpaceComplete.tsx
  src/shared/component/createWorkSpace/image/WorkSpaceImage.style.ts
  src/shared/component/createWorkSpace/info/WorkSpaceInfo.style.ts
  src/shared/component/createWorkSpace/info/WorkSpaceInfo.tsx
  src/shared/component/createWorkSpace/name/WorkSpaceName.style.ts
  src/shared/constant/index.ts
  src/story/shared/DeleteModal.stories.tsx
Labels: ✨Feature, 🍀채원, 💄Design

#86 [Feat] 왼쪽 사이드바 호버 및 애니메이션 구현
  src/App.tsx
  src/common/asset/svg/add.svg
  src/common/asset/svg/arrow-left.svg
  src/common/asset/svg/arrow-right.svg
  src/common/asset/svg/earth.svg
  src/common/asset/svg/logo_symbol.svg
  src/common/asset/svg/polder.svg
  src/shared/component/LeftSidebar/LeftSidebar.style.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/ClickStick/ClickStick.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/ClickStick/ClickStick.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.tsx
  src/shared/component/constant/index.ts
Labels: ✨Feature

#83 [Feat] 전체문서 바 뷰 구현
  src/common/asset/svg/arrow-down-thin.svg
  src/common/asset/svg/arrow-up-thin.svg
  src/common/asset/svg/arrow-up.svg
  src/common/asset/svg/arrow.svg
  src/common/component/Input/Input.style.ts
  src/common/component/Select/Select.style.ts
  src/page/archiving/component/DocumentBar/DocumentBar.style.ts
  src/page/archiving/component/DocumentBar/DocumentBar.tsx
  src/page/archiving/component/DocumentBar/DocumentWrapper/DocumentBarTool/DocumentBarTool.tsx
  src/page/archiving/component/DocumentBar/DocumentWrapper/DocumentBarTool/DocumentSort/DocumentSort.style.ts
  src/page/archiving/component/DocumentBar/DocumentWrapper/DocumentBarTool/DocumentSort/DocumentSort.tsx
  src/page/archiving/component/DocumentBar/DocumentWrapper/DocumentBarTool/DocumentSort/FilterDropdown/Filter.style.ts
  src/page/archiving/component/DocumentBar/DocumentWrapper/DocumentBarTool/DocumentSort/FilterDropdown/Filter.tsx
  src/page/archiving/component/DocumentBar/DocumentWrapper/DocumentWrapper.tsx
  src/story/page/archiving/DocumentBar/DocumentBarTab.stories.tsx
  src/story/page/archiving/DocumentBar/DocumentItem.stories.tsx
Labels: ✨Feature, 🍭규홍

#79 [Feat] showcase페이지 퍼블리싱
  package.json
  pnpm-lock.yaml
  src/common/asset/img/advBannerClub1.png
  src/common/asset/img/advBannerClub2.png
  src/common/asset/img/advBannerClub3.png
  src/common/asset/img/advBannerClub4.png
  src/common/asset/svg/arrow-left-white.svg
  src/common/asset/svg/arrow-right-white.svg
  src/common/router/Router.tsx
  src/page/showcase/ShowcasePage.style.ts
  src/page/showcase/ShowcasePage.tsx
  src/page/showcase/component/AdvBanner/AdvBanner.style.ts
  src/page/showcase/component/AdvBanner/AdvBanner.tsx
  src/page/showcase/component/BannerSlider/BannerSlider.style.ts
  src/page/showcase/component/BannerSlider/BannerSlider.tsx
  src/page/showcase/component/CategoryChip/CategoryChip.style.ts
  src/page/showcase/component/CategoryChip/CategoryChip.tsx
  src/page/showcase/component/ClubProfileCard/ClubProfileCard.style.ts
  src/page/showcase/constant/category.ts
  src/story/page/showcase/BannerSlider.stories.tsx
  src/story/page/showcase/ShowcasePage.stories.tsx
Labels: ✨Feature, 🤍보운, 💄Design

#91 [Init] Mock 데이터 세팅
  src/mock/data/showCase.ts
  src/mock/data/timeLine.ts
  src/mock/handler/index.ts
  src/mock/handler/showCase.ts
  src/mock/handler/timeLine.ts
  src/mock/handler/workspace.ts
  src/shared/api/instance.ts
Labels: ⭐️주용, ✨Feature, 🔗Init

#96 [Feat] 문서 검색 구현
  src/App.tsx
  src/page/archiving/component/DocumentBar/DocumentBar.tsx
  src/page/archiving/component/DocumentBar/DocumentWrapper/DocumentWrapper.tsx
  src/page/archiving/component/DocumentBar/constant/index.ts
  src/page/archiving/component/DocumentBarInfo/DocumentBarInfo.style.ts
  src/page/archiving/component/DocumentBarInfo/DocumentBarInfo.tsx
  src/page/archiving/component/DocumentBarTab/DocumentBarTab.style.ts
  src/page/archiving/component/DocumentBarTab/DocumentBarTab.tsx
  src/page/archiving/component/DocumentBarTool/DocumentBarTool.tsx
  src/page/archiving/component/DocumentFilter/DocumentFilter.style.ts
  src/page/archiving/component/DocumentFilter/DocumentFilter.tsx
  src/page/archiving/component/DocumentItem/DocumentItem.style.ts
  src/page/archiving/component/DocumentItem/DocumentItem.tsx
  src/page/archiving/component/DocumentSort/DocumentSort.style.ts
  src/page/archiving/component/DocumentSort/DocumentSort.tsx
  src/page/archiving/component/DocumentWrapper/DocumentWrapper.style.ts
  src/page/archiving/component/DocumentWrapper/DocumentWrapper.tsx
  src/page/archiving/constant/document.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.style.ts
Labels: ✨Feature, 🍭규홍

#98 [Refactor] 랜딩 페이지 퍼블리싱 디벨롭 + 인터섹션 옵저버 적용
  package.json
  pnpm-lock.yaml
  src/common/asset/img/landing01.png
  src/common/asset/img/landing02.png
  src/common/asset/img/service01.png
  src/common/asset/img/service02.png
  src/common/asset/json/landing_ani.json
  src/common/hook/useObserver.ts
  src/common/style/theme/theme.ts
  src/page/landing/LandingPage.style.ts
  src/page/landing/LandingPage.tsx
  src/page/landing/component/FeatureSection/FeatureSection.style.ts
  src/page/landing/component/FeatureSection/FeatureSection.tsx
  src/page/landing/component/Overview/Overview.style.ts
  src/page/landing/component/Overview/Overview.tsx
  src/page/landing/constant/index.ts
  src/shared/store/auth.ts
  src/story/page/landing/Overview.stories.tsx
Labels: ⭐️주용, ✨Feature, 💄Design

#101 [Design] 로그인/회원가입 뷰 디벨롭
  src/common/asset/svg/arrow-down.svg
  src/common/asset/svg/logo_tiki_md.svg
  src/common/component/Button/Button.style.ts
  src/common/component/Label/Label.style.ts
  src/common/component/Select/Select.style.ts
  src/common/router/Router.tsx
  src/common/style/theme/theme.ts
  src/page/login/LoginPage.style.ts
  src/page/login/LoginPage.tsx
  src/page/signIn/index/TermPage.tsx
  src/page/signIn/info/InfoFormPage.style.ts
  src/page/signIn/info/InfoFormPage.tsx
  src/page/signUp/index/TermPage.style.ts
  src/page/signUp/index/TermPage.tsx
  src/page/signUp/index/component/TermArea/TermArea.style.ts
  src/page/signUp/index/component/TermArea/TermArea.tsx
  src/page/signUp/index/component/TermsAgreeButton/TermsAgreeButton.style.ts
  src/page/signUp/index/component/TermsAgreeButton/TermsAgreeButton.tsx
  src/page/signUp/info/InfoFormPage.style.ts
  src/page/signUp/info/InfoFormPage.tsx
  src/page/signUp/info/constant/index.ts
  src/page/signUp/info/util/formatTime.ts
  src/page/signUp/password/PasswordPage.style.ts
  src/page/signUp/password/PasswordPage.tsx
  src/story/page/signUp/InfoFormPage.stories.tsx
  src/story/page/signUp/TermArea.stories.tsx
  src/story/page/signUp/TermPage.stories.tsx
  src/story/page/signUp/TermsAgreeButton.stories.tsx
Labels: 💫다은, 💄Design

#85 [Feat] 아카이빙 페이지 리팩토링 & 우측 사이드 메뉴 붙이기
  src/App.tsx
  src/common/component/Header/Header.style.ts
  src/page/archiving/ArchivingPage.style.ts
  src/page/archiving/ArchivingPage.tsx
  src/page/archiving/component/DaySection/DaySection.style.ts
  src/page/archiving/component/DaySection/DaySection.tsx
  src/page/archiving/component/DocumentBar/DocumentBar.style.ts
  src/page/archiving/component/DocumentBar/DocumentBar.tsx
  src/page/archiving/component/MonthHeader/MonthHeader.style.ts
  src/page/archiving/component/MonthHeader/MonthHeader.tsx
  src/page/archiving/component/TimeBlock/TimeBlock.style.ts
  src/page/archiving/component/TimeBlock/TimeBlock.tsx
  src/page/archiving/component/YearHeader/YearHeader.style.ts
  src/page/archiving/component/YearHeader/YearHeader.tsx
  src/page/archiving/constant/timeBlock.ts
  src/page/archiving/hook/useDate.ts
  src/page/archiving/type/blockType.ts
  src/page/archiving/util/alignBlocks.ts
  src/page/archiving/util/formattingDate.ts
  src/story/page/archiving/DaySection.stories.tsx
  src/story/page/archiving/MonthHeader.stories.tsx
  src/story/page/archiving/TimeBlock.stories.tsx
Labels: ♻️Refactor, 💫다은, ✨Feature

#90 [Design] 왼쪽 사이드바 붙이기 & 배경테두리
  src/App.tsx
  src/common/component/Header/Header.style.ts
  src/common/component/Modal/Modal.tsx
  src/common/hook/useModal.tsx
  src/common/router/Router.tsx
  src/common/style/globalStyle.ts
  src/page/archiving/ArchivingPage.style.ts
  src/page/archiving/ArchivingPage.tsx
  src/page/archiving/component/DocumentBar/DocumentBar.style.ts
  src/page/showcase/ShowcasePage.style.ts
  src/shared/component/LeftSidebar/LeftSidebar.style.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.tsx
  src/shared/component/constant/index.ts
Labels: 🍀채원, 💄Design

#103 [Feat] 블록 문서 정보 get 받아오기 & 문서 바 애니메이션 & outSideClick 구현
  src/common/hook/useOutsideClick.ts
  src/page/archiving/ArchivingPage.tsx
  src/page/archiving/component/DocumentBar/DocumentBar.style.ts
  src/page/archiving/component/DocumentBar/DocumentBar.tsx
  src/page/archiving/component/DocumentBarInfo/DocumentBarInfo.tsx
  src/page/archiving/component/DocumentBarTab/DocumentBarTab.style.ts
  src/page/archiving/component/DocumentWrapper/DocumentWrapper.tsx
  src/page/archiving/component/MonthHeader/MonthHeader.style.ts
  src/page/archiving/constant/document.ts
  src/shared/api/archiving/document/index.ts
  src/shared/api/archiving/document/type.ts
  src/shared/api/hook/useBlockQuery.ts
  src/shared/api/instance.ts
  src/story/page/archiving/DocumentBar/DocumentItem.stories.tsx
Labels: ✨Feature, 🍭규홍

#105 [Feat] 비밀번호 재설정 & 인증 페이지 뷰 구현
  package.json
  pnpm-lock.yaml
  src/common/router/Router.tsx
  src/page/login/LoginPage.tsx
  src/page/login/hook/useTimer.ts
  src/page/login/passwordAuth/PasswordAuthPage.style.ts
  src/page/login/passwordAuth/PasswordAuthPage.tsx
  src/page/login/passwordReset/PasswordResetPage.style.ts
  src/page/login/passwordReset/PasswordResetPage.tsx
  src/page/login/util/validateInput.ts
  src/page/signUp/info/constant/index.ts
Labels: 💫다은, ✨Feature

#110 [Feat] 회원가입 POST API 연결
  src/common/router/Router.tsx
  src/page/signUp/index/TermPage.tsx
  src/page/signUp/index/component/TermArea/TermArea.tsx
  src/page/signUp/info/InfoFormPage.style.ts
  src/page/signUp/info/InfoFormPage.tsx
  src/page/signUp/info/component/InfoForm/InfoForm.style.ts
  src/page/signUp/info/component/InfoForm/InfoForm.tsx
  src/page/signUp/info/component/PasswordForm/PasswordForm.tsx
  src/page/signUp/info/constant/index.ts
  src/page/signUp/info/hook/useDateInput.ts
  src/page/signUp/info/hook/useInput.ts
  src/page/signUp/info/hook/useSelect.ts
  src/page/signUp/info/hook/useSignupMutation.ts
  src/page/signUp/info/hook/useTimer.ts
  src/page/signUp/info/util/date.ts
  src/page/signUp/info/util/formatTime.ts
  src/page/signUp/password/PasswordPage.style.ts
  src/page/signUp/password/PasswordPage.tsx
  src/shared/api/index.d.ts
  src/shared/api/queryClient.ts
  src/shared/api/signup/info/index.ts
  src/shared/api/signup/info/type.ts
  src/story/page/landing/LandingFeatureSection.stories.tsx
  src/story/page/landing/Overview.stories.tsx
  tsconfig.json
Labels: ⭐️주용, ✨Feature

#106 [Feat] coming soon page 퍼블리싱
  src/common/asset/img/comingsoon.png
  src/common/asset/img/error.png
  src/common/router/Router.tsx
  src/page/showcase/ShowcasePage.tsx
  src/page/showcase/component/ClubProfileCard/ClubProfileCard.tsx
  src/shared/page/comingsoonPage/ComingsoonPage.tsx
Labels: ✨Feature, 🤍보운, 💄Design

#109 [Feat] error page publishing
  src/common/router/Router.tsx
  src/shared/page/errorPage/ErrorPage.tsx
Labels: ✨Feature, 🤍보운, 💄Design

#115 [Refactor] documentBar 리펙토링
  src/page/archiving/component/DocumentBar/DocumentBar.tsx
  src/page/archiving/component/DocumentBarInfo/DocumentBarInfo.style.ts
  src/page/archiving/component/DocumentBarInfo/DocumentBarInfo.tsx
  src/page/archiving/component/DocumentBarTab/DocumentBarTab.tsx
  src/page/archiving/component/DocumentBarTool/DocumentBarTool.tsx
  src/page/archiving/component/DocumentItem/DocumentItem.tsx
  src/page/archiving/component/DocumentSort/DocumentSort.style.ts
  src/page/archiving/component/DocumentSort/DocumentSort.tsx
  src/page/archiving/component/DocumentWrapper/DocumentWrapper.style.ts
  src/page/archiving/component/DocumentWrapper/DocumentWrapper.tsx
  src/page/archiving/component/SelectedBlock/SelectedBlock.style.ts
  src/page/archiving/component/SelectedBlock/SelectedBlock.tsx
  src/page/archiving/component/TotalDocument/TotalDocument.style.ts
  src/page/archiving/component/TotalDocument/TotalDocument.tsx
  src/shared/api/archiving/document/index.ts
  src/shared/api/archiving/document/type.ts
  src/shared/api/hook/useBlockQuery.ts
  src/shared/api/hook/useTotalDocumentQuery.ts
Labels: ♻️Refactor, 🍭규홍

#117 [Refactor] 전반적인 컴포넌트 및 라우트 리팩토링
  src/App.tsx
  src/common/asset/svg/landing_indicator.svg
  src/common/router/Router.tsx
  src/page/landing/LandingPage.tsx
  src/page/login/index/LoginPage.style.ts
  src/page/login/index/LoginPage.tsx
  src/page/login/password/hook/useTimer.ts
  src/page/login/password/passwordAuth/PasswordAuthPage.style.ts
  src/page/login/password/passwordAuth/PasswordAuthPage.tsx
  src/page/login/password/passwordReset/PasswordResetPage.style.ts
  src/page/login/password/passwordReset/PasswordResetPage.tsx
  src/page/login/password/util/validateInput.ts
  src/page/showcase/index/ShowcasePage.style.ts
  src/page/showcase/index/ShowcasePage.tsx
  src/page/showcase/index/component/AdvBanner/AdvBanner.style.ts
  src/page/showcase/index/component/AdvBanner/AdvBanner.tsx
  src/page/showcase/index/component/BannerSlider/BannerSlider.style.ts
  src/page/showcase/index/component/BannerSlider/BannerSlider.tsx
  src/page/showcase/index/component/CategoryChip/CategoryChip.style.ts
  src/page/showcase/index/component/CategoryChip/CategoryChip.tsx
  src/page/showcase/index/component/ClubProfileCard/ClubProfileCard.style.ts
  src/page/showcase/index/component/ClubProfileCard/ClubProfileCard.tsx
  src/page/showcase/index/constant/category.ts
  src/page/showcase/team/index.tsx
  src/shared/constant/path.ts
Labels: ⭐️주용, ♻️Refactor

#120 [Feat] 스낵바 컴포넌트 생성, 컨테이너/팩토리 전역에 연결
  src/common/asset/json/landing_ani.json
  src/common/asset/svg/caution.svg
  src/common/asset/svg/success.svg
  src/common/component/Toast/Toast.style.ts
  src/common/component/Toast/Toast.tsx
  src/common/component/ToastContainer/ToastContainer.style.ts
  src/common/component/ToastContainer/ToastContainer.tsx
  src/common/component/ToastContainer/ToastProvider.tsx
  src/common/style/animation.ts
  src/main.tsx
  src/page/showcase/index/component/AdvBanner/AdvBanner.tsx
  src/page/showcase/index/component/BannerSlider/BannerSlider.tsx
  src/page/showcase/index/component/CategoryChip/CategoryChip.tsx
  src/page/signUp/info/hook/useTimer.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/store/toast.ts
  src/shared/type/time.ts
  src/shared/type/toast.ts
  src/story/common/Toast.stories.tsx
  src/story/page/login/LoginPage.stories.tsx
  src/story/page/showcase/AdvBanner.stories.tsx
  src/story/page/showcase/BannerSlider.stories.tsx
  src/story/page/showcase/CategoryChip.stories.tsx
  src/story/page/showcase/ClubProfileCard.stories.tsx
  src/story/page/showcase/ShowcasePage.stories.tsx
  src/story/shared/DeleteModal.stories.tsx
Labels: ⭐️주용, ✨Feature

#123 소속 동아리 정보 가져오기 api 연결
  src/page/archiving/ArchivingPage.tsx
  src/page/archiving/component/DocumentBar/DocumentBar.tsx
  src/page/archiving/component/SelectedBlock/SelectedBlock.tsx
  src/page/archiving/component/TotalDocument/TotalDocument.tsx
  src/page/archiving/hook/api/useBlockQuery.ts
  src/page/archiving/hook/api/useTotalDocumentQuery.ts
  src/page/archiving/hook/common/useDate.ts
  src/page/archiving/hook/common/useDateRange.tsx
  src/page/archiving/hook/common/useFile.tsx
  src/page/archiving/type/documentType.ts
  src/shared/api/archiving/document/index.ts
  src/shared/api/documents/team/timeline/index.ts
  src/shared/api/documents/team/timeline/type.ts
  src/shared/api/members/teams/index.ts
  src/shared/api/members/teams/type.ts
  src/shared/api/time-blocks/team/time-block/index.ts
  src/shared/api/time-blocks/team/time-block/type.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.tsx
  src/shared/component/constant/index.ts
  src/shared/constant/index.ts
  src/shared/hook/api/useClubInfoQuery.ts
  src/shared/type/team.ts
Labels: ✨Feature, 🍭규홍

#124 [Feat] 동아리 리스트, 카테고리리스트 GET api
  src/page/showcase/index/ShowcasePage.style.ts
  src/page/showcase/index/ShowcasePage.tsx
  src/page/showcase/index/component/ClubProfileCard/ClubProfileCard.style.ts
  src/page/showcase/index/constant/category.ts
  src/shared/api/teams/category/index.ts
  src/shared/api/teams/category/type.ts
  src/shared/api/teams/index.ts
  src/shared/api/teams/type.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/hook/useCategoryListQuery.ts
  src/shared/hook/useClubListQuery.ts
  src/shared/page/comingsoonPage/ComingsoonPage.tsx
  src/shared/page/errorPage/ErrorPage.tsx
Labels: ✨Feature, 🤍보운, 💄Design

#130 [Feat] 로그인 API 연결, JWT 토큰 관리
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/common/component/ErrorBoundary/ErrorBoundary.tsx
  src/common/component/ToastContainer/ToastContainer.style.ts
  src/common/router/Router.tsx
  src/page/login/index/LoginPage.tsx
  src/page/login/index/constant/index.ts
  src/page/login/index/hook/useLoginMutation.ts
  src/page/signUp/info/InfoFormPage.tsx
  src/shared/api/auth/reissue/index.ts
  src/shared/api/auth/signin/index.ts
  src/shared/api/auth/signin/type.ts
  src/shared/api/instance.ts
  src/shared/api/interceptor.ts
  src/shared/api/signup/info/index.ts
  src/shared/component/Login/Login.tsx
  src/shared/constant/api.ts
  src/shared/constant/path.ts
  src/shared/hook/common/useLogout.ts
  src/shared/page/comingsoonPage/ComingsoonPage.tsx
  src/shared/page/errorPage/ErrorPage.style.ts
  src/shared/page/errorPage/ErrorPage.tsx
Labels: ⭐️주용, ✨Feature

#134 워크스페이스 생성을 위한 api 들 연결 및 오류 수정
  src/common/asset/svg/arrow_drop_down.svg
  src/common/component/Modal/Modal.tsx
  src/common/hook/useOutsideClick.ts
  src/page/archiving/createTimeBlock/component/Upload/File/Add/BlockAdd.tsx
  src/page/archiving/createTimeBlock/component/Upload/UploadModal.tsx
  src/page/archiving/createTimeBlock/hook/api/usePostTimeBlockMutation.ts
  src/page/archiving/createTimeBlock/hook/common/useFile.tsx
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DocumentBar/DocumentBar.tsx
  src/page/archiving/index/component/SelectedBlock/SelectedBlock.tsx
  src/shared/api/file/index.ts
  src/shared/api/file/upload/index.ts
  src/shared/api/instance.ts
  src/shared/api/queryClient.ts
  src/shared/api/teams/index.ts
  src/shared/api/teams/type.ts
  src/shared/api/time-blocks/team/time-block/index.ts
  src/shared/api/time-blocks/team/time-block/type.ts
  src/shared/component/LeftSidebar/LeftSidebar.style.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.tsx
  src/shared/component/createWorkSpace/category/WorkSpaceCategory.style.ts
  src/shared/component/createWorkSpace/category/WorkSpaceCategory.tsx
  src/shared/component/createWorkSpace/complete/WorkSpaceComplete.tsx
  src/shared/component/createWorkSpace/hook/api/useGetFileQuery.ts
  src/shared/component/createWorkSpace/hook/api/usePostTeamMutation.ts
  src/shared/component/createWorkSpace/image/WorkSpaceImage.tsx
  src/shared/component/createWorkSpace/name/WorkSpaceName.tsx
  src/story/common/Modal.stories.tsx
Labels: ✨Feature, 🍀채원

#131 [Feat] left side bar의 환경설정 버튼 구현
  src/common/asset/svg/logout.svg
  src/common/asset/svg/password.svg
  src/common/asset/svg/settings.svg
  src/page/showcase/index/ShowcasePage.tsx
  src/page/showcase/index/component/AdvBanner/AdvBanner.style.ts
  src/page/showcase/index/component/BannerSlider/BannerSlider.style.ts
  src/page/showcase/index/component/BannerSlider/BannerSlider.tsx
  src/shared/api/instance.ts
  src/shared/api/teams/category/index.ts
  src/shared/component/LeftSidebar/LeftSidebar.style.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/SettingModal/SettingModal.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/SettingModal/SettingModal.tsx
  src/shared/hook/useCategoryListQuery.ts
  src/shared/hook/useClubListQuery.ts
Labels: ✨Feature, 🤍보운

#133 [Feat] 문서, 블록 삭제 api 구현 및 각종 오류 해결
  src/common/component/Modal/Modal.tsx
  src/page/archiving/index/ArchivingPage.style.ts
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DocumentBar/DocumentBar.style.ts
  src/page/archiving/index/component/DocumentBar/DocumentBar.tsx
  src/page/archiving/index/component/DocumentItem/DocumentItem.style.ts
  src/page/archiving/index/component/DocumentItem/DocumentItem.tsx
  src/page/archiving/index/component/DocumentSort/DocumentSort.tsx
  src/page/archiving/index/component/MonthHeader/MonthHeader.style.ts
  src/page/archiving/index/component/MonthHeader/MonthHeader.tsx
  src/page/archiving/index/component/SelectedBlock/SelectedBlock.tsx
  src/page/archiving/index/component/TotalDocument/TotalDocument.tsx
  src/page/archiving/index/constant/document.ts
  src/page/archiving/index/hook/api/useDeleteBlockMutaion.ts
  src/page/archiving/index/hook/api/useDeleteDocumentMutation.ts
  src/page/archiving/index/hook/api/useTotalDocumentQuery.ts
  src/page/archiving/index/type/blockType.ts
  src/page/archiving/index/type/documentType.ts
  src/shared/api/documents/team/document/index.ts
  src/shared/api/documents/team/timeline/type.ts
  src/shared/api/time-blocks/team/time-block/index.ts
  src/shared/component/DeleteModal/DeleteModal.tsx
  src/story/page/archiving/DocumentBar/DocumentItem.stories.tsx
Labels: ✨Feature, 🍭규홍

#119 [Feat] 비밀번호 이메일 POST & 인증코드 POST
  src/common/hook/useInput.ts
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/hook/api/useGetTimeBlockQuery.ts
  src/page/login/constant/index.ts
  src/page/login/password/hook/useSendMailMutation.ts
  src/page/login/password/hook/useVerifyCodeMutation.ts
  src/page/login/password/passwordAuth/PasswordAuthPage.style.ts
  src/page/login/password/passwordAuth/PasswordAuthPage.tsx
  src/page/login/password/passwordReset/PasswordResetPage.style.ts
  src/page/login/password/passwordReset/PasswordResetPage.tsx
  src/page/login/password/util/validateInput.ts
  src/page/signUp/info/InfoFormPage.tsx
  src/page/signUp/info/component/InfoForm/InfoForm.tsx
  src/page/signUp/info/component/PasswordForm/PasswordForm.tsx
  src/page/signUp/info/constant/index.ts
  src/page/signUp/info/hook/api/useSendMailMutation.ts
  src/page/signUp/info/hook/api/useSignupMutation.ts
  src/page/signUp/info/hook/common/useDateInput.ts
  src/page/signUp/info/hook/common/useSelect.ts
  src/page/signUp/info/hook/common/useTimer.ts
  src/shared/api/mail/checking/index.ts
  src/shared/api/mail/signup/index.ts
  src/shared/api/queryClient.ts
  src/story/page/archiving/TimeBlock.stories.tsx
Labels: 💫다은, ✨Feature

#142 [Refactor] redirect PATH 및 라우터 수정
  src/common/router/Router.tsx
  src/shared/api/interceptor.ts
  src/shared/component/Login/Login.tsx
  src/shared/constant/path.ts
Labels: ⭐️주용, 💥Hotfix

#143 [Fix] axiosInstance 에러 해결
  src/page/signUp/info/InfoFormPage.tsx
  src/page/signUp/info/component/InfoForm/InfoForm.tsx
  src/shared/api/mail/checking/index.ts
  src/shared/api/mail/password/index.ts
  src/shared/api/mail/signup/index.ts
  src/shared/api/members/password/index.ts
Labels: 💫다은, 🐛Bug

#147 [Feat] 파일 다운로드 기능 딸깍
  src/page/archiving/index/component/DocumentItem/DocumentItem.tsx
  src/page/archiving/index/component/SelectedBlock/SelectedBlock.tsx
  src/page/archiving/index/util/document.ts
Labels: ✨Feature, 🍭규홍

#148 Fix/tiki/#138 fix qa
  src/page/login/password/hook/api/useResendMailMutation.ts
  src/page/login/password/hook/api/useSendMailMutation.ts
  src/page/login/password/hook/api/useVerifyCodeMutation.ts
  src/page/signUp/info/InfoFormPage.tsx
  src/page/signUp/info/component/InfoForm/InfoForm.tsx
  src/page/signUp/info/component/PasswordForm/PasswordForm.tsx
  src/page/signUp/info/hook/api/useSendMailMutation.ts
Labels: 💫다은, 🐛Bug

#153 [Hotfix] 로그인 회원가입 시 디자인 시스템과 다른 부분 수정, UX 디벨롭
  src/common/asset/img/landing01.png
  src/common/asset/img/landing02.png
  src/common/asset/img/service02.png
  src/common/asset/svg/check.svg
  src/common/asset/svg/check_active.svg
  src/common/component/Button/Button.style.ts
  src/common/component/Toast/Toast.style.ts
  src/common/router/Router.tsx
  src/common/style/globalStyle.ts
  src/main.tsx
  src/page/landing/LandingPage.style.ts
  src/page/landing/LandingPage.tsx
  src/page/signUp/index/TermPage.style.ts
  src/page/signUp/index/TermPage.tsx
  src/page/signUp/index/component/TermArea/TermArea.tsx
  src/page/signUp/index/constant/index.ts
  src/page/signUp/info/component/InfoForm/InfoForm.style.ts
  src/page/signUp/info/component/InfoForm/InfoForm.tsx
  src/page/signUp/info/component/PasswordForm/PasswordForm.tsx
  src/page/signUp/info/constant/index.ts
  src/page/signUp/info/hook/api/useSendMailMutation.ts
  src/page/signUp/info/hook/common/useSelect.ts
  src/page/signUp/info/hook/common/useTimer.ts
  src/shared/page/errorPage/ErrorPage.style.ts
Labels: ⭐️주용, 💥Hotfix

#152 [Style] 쇼케이스 QA, 환경설정 버튼 구현
  src/page/showcase/index/ShowcasePage.tsx
  src/page/showcase/index/component/AdvBanner/AdvBanner.style.ts
  src/page/showcase/index/component/ClubProfileCard/ClubProfileCard.style.ts
  src/page/showcase/index/constant/banner.ts
  src/page/signUp/info/hook/api/useSendMailMutation.ts
  src/shared/component/LeftSidebar/LeftSidebar.style.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/SettingMenu/SettingMenu.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/SettingMenu/SettingMenu.tsx
  src/shared/hook/api/useCategoryListQuery.ts
Labels: ✨Feature, 🤍보운, 💄Design

#156 모달 QA
  src/common/asset/svg/accounting_icon.svg
  src/common/asset/svg/event_icon.svg
  src/common/asset/svg/meeting_icon.svg
  src/common/asset/svg/notice_icon.svg
  src/common/asset/svg/spinner.svg
  src/common/asset/svg/study_icon.svg
  src/common/asset/svg/task_icon.svg
  src/common/component/Spinner/Spinner.tsx
  src/page/archiving/createTimeBlock/component/Block/BlockModal.tsx
  src/page/archiving/createTimeBlock/component/Block/Date/BlockDate.tsx
  src/page/archiving/createTimeBlock/component/Block/Icon/BlockIcon.style.ts
  src/page/archiving/createTimeBlock/component/Block/Icon/BlockIcon.tsx
  src/page/archiving/createTimeBlock/component/Upload/File/Add/BlockAdd.tsx
  src/page/archiving/createTimeBlock/component/Upload/File/List/BlockItem.style.ts
  src/page/archiving/createTimeBlock/component/Upload/File/List/BlockItem.tsx
  src/page/archiving/createTimeBlock/component/Upload/UploadModal.tsx
  src/page/archiving/createTimeBlock/constant/error.ts
  src/page/archiving/createTimeBlock/constant/icon.ts
  src/page/archiving/createTimeBlock/constant/iconBlock.tsx
  src/page/archiving/createTimeBlock/hook/common/useFile.tsx
  src/page/archiving/createTimeBlock/util/date.ts
  src/page/archiving/index/constant/color.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/createWorkSpace/category/WorkSpaceCategory.tsx
  src/shared/component/createWorkSpace/image/WorkSpaceImage.tsx
  src/story/page/archiving/modal/BlockItem.stories.tsx
Labels: ♻️Refactor, 🐛Bug, 🍀채원, 💄Design

#151 사이드바 QA 반영
  src/common/asset/svg/add_2.svg
  src/common/asset/svg/books.svg
  src/common/asset/svg/global_2.svg
  src/common/asset/svg/money.svg
  src/common/asset/svg/party.svg
  src/common/asset/svg/people.svg
  src/common/asset/svg/setting.svg
  src/common/asset/svg/settings.svg
  src/common/asset/svg/speaker.svg
  src/common/asset/svg/teamprofile_2.svg
  src/common/asset/svg/teamprofile_default.svg
  src/page/archiving/createTimeBlock/component/Upload/UploadModal.tsx
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DocumentItem/DocumentItem.style.ts
  src/page/archiving/index/component/DocumentSort/DocumentSort.tsx
  src/page/archiving/index/component/SelectedBlock/SelectedBlock.style.ts
  src/page/archiving/index/component/SelectedBlock/SelectedBlock.tsx
  src/page/archiving/index/component/TimeBlock/TimeBlock.tsx
  src/page/archiving/index/component/TotalDocument/TotalDocument.style.ts
  src/page/archiving/index/component/TotalDocument/TotalDocument.tsx
  src/page/archiving/index/constant/icon.tsx
  src/shared/component/LeftSidebar/LeftSidebar.style.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.tsx
  src/shared/constant/index.ts
Labels: 🐛Bug, 🍭규홍

#159 [Feat] 타임라인 QA 수정
  src/page/archiving/createTimeBlock/component/Upload/UploadModal.tsx
  src/page/archiving/index/ArchivingPage.style.ts
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/hook/api/useGetTimeBlockQuery.ts
  src/page/archiving/index/hook/common/useDate.ts
  src/page/archiving/index/util/block.ts
Labels: 💫다은, 🐛Bug

#157 [Refactor] 타임라인 QA
  src/common/asset/svg/dotted_line.svg
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DaySection/DaySection.style.ts
  src/page/archiving/index/component/DaySection/DaySection.tsx
  src/page/archiving/index/component/TimeBlock/TimeBlock.style.ts
  src/page/archiving/index/component/TimeBlock/TimeBlock.tsx
Labels: ⭐️주용, ♻️Refactor

#158 [Refactor] Router 및 페이지 리다이렉션 구조 수정
  .storybook/preview.tsx
  README.md
  src/common/component/Toast/Toast.style.ts
  src/common/router/Router.tsx
  src/mock/data/term.ts
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/TimeBlock/TimeBlock.tsx
  src/page/landing/LandingPage.tsx
  src/page/login/index/LoginPage.tsx
  src/page/login/password/passwordAuth/PasswordAuthPage.tsx
  src/page/login/password/passwordReset/PasswordResetPage.tsx
  src/page/showcase/index/component/BannerSlider/BannerSlider.tsx
  src/page/signUp/index/TermPage.style.ts
  src/page/signUp/index/TermPage.tsx
  src/page/signUp/info/InfoFormPage.tsx
  src/page/signUp/info/component/InfoForm/InfoForm.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/SettingMenu/SettingMenu.tsx
  src/shared/constant/path.ts
  src/story/page/signUp/TermArea.stories.tsx
Labels: ⭐️주용, ♻️Refactor

#164 [refactor] 모달 TASK 오류 수정
  src/page/archiving/createTimeBlock/constant/iconBlock.tsx
Labels: 🍀채원, 💥Hotfix

#163 [Design] 타임라인 스타일 수정
  src/page/archiving/index/ArchivingPage.style.ts
  src/page/archiving/index/component/DaySection/DaySection.style.ts
  src/page/archiving/index/component/DaySection/DaySection.tsx
  src/page/archiving/index/component/TimeBlock/TimeBlock.style.ts
Labels: 💫다은, 💄Design

#171 [Fix] 레싸바 오류 해결
  src/page/archiving/index/component/TotalDocument/TotalDocument.tsx
  src/shared/component/LeftSidebar/LeftSidebar.style.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.tsx
  src/shared/constant/index.ts
Labels: 🍭규홍, 💥Hotfix

#173 [Fix] 타임 블록 달 겹치는 경우 쌓기
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/util/block.ts
Labels: 💫다은, 🐛Bug

#174 [Hotfix] TimeLine 뷰 QA
  src/page/archiving/index/ArchivingPage.style.ts
  src/page/archiving/index/component/DaySection/DaySection.style.ts
  src/page/archiving/index/component/DaySection/DaySection.tsx
  src/page/archiving/index/component/TimeBlock/TimeBlock.style.ts
  src/page/archiving/index/component/YearHeader/YearHeader.tsx
Labels: ⭐️주용, 💥Hotfix

#178 [Feature] 타임라인 블록 클릭 시 중앙으로 스크롤 구현, 랜딩 페이지 화살표로 뷰 전환 구현
  src/common/asset/svg/arrow_fill.svg
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/TimeBlock/TimeBlock.tsx
  src/page/landing/LandingPage.style.ts
  src/page/landing/LandingPage.tsx
  src/page/landing/component/Indicator/Indicator.tsx
  src/page/landing/component/Overview/Overview.style.ts
  src/page/landing/component/Overview/Overview.tsx
Labels: ⭐️주용, ✨Feature

#179 [Hotfix] 타임라인 scrollIntoView 될 시 부모 요소 스크롤 방지, 현재 날짜 섹션의 dashed line 클릭 이벤트 막기
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DaySection/DaySection.tsx
Labels: ⭐️주용, 💥Hotfix

#182 [Feat] 검색 기능 디바운싱 적용 및 document 바 state 위치 조정
  src/common/hook/useDebounce.ts
  src/page/archiving/index/component/DocumentBar/DocumentBar.tsx
  src/page/archiving/index/component/SelectedBlock/SelectedBlock.tsx
  src/page/archiving/index/component/TotalDocument/TotalDocument.tsx
  src/page/archiving/index/hook/api/useBlockQuery.ts
  src/page/archiving/index/hook/api/useTotalDocumentQuery.ts
  src/page/archiving/index/type/documentType.ts
Labels: ✨Feature, 🍭규홍
