Repository Team-Tiki/tiki-client, pull requests merged in 2024-08, with the labels that each got.

#183 [Feat] 액세스 토큰 없을 시, 리프레시 토큰을 통해 재발급하는 인터셉터 구현 / Public 라우트는 인증 회원에게 방어하지 않도록 수정
  src/common/router/Router.tsx
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/hook/api/useBlockQuery.ts
  src/page/landing/LandingPage.tsx
  src/page/login/index/LoginPage.tsx
  src/shared/api/auth/reissue/index.ts
  src/shared/api/instance.ts
  src/shared/api/interceptor.ts
  src/shared/component/LeftSidebar/LeftSidebar.style.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/Login/Login.tsx
Labels: ⭐️주용, ✨Feature

#191 [Refactor] css 리펙토링
  src/page/archiving/index/component/DocumentBar/DocumentBar.style.ts
  src/page/archiving/index/component/DocumentBarTab/DocumentBarTab.style.ts
  src/page/archiving/index/component/DocumentBarTab/DocumentBarTab.tsx
  src/page/archiving/index/component/DocumentFilter/DocumentFilter.style.ts
  src/page/archiving/index/component/DocumentItem/DocumentItem.style.ts
  src/page/archiving/index/component/DocumentSort/DocumentSort.style.ts
  src/page/archiving/index/component/SelectedBlock/SelectedBlock.style.ts
  src/page/archiving/index/component/SelectedBlock/SelectedBlock.tsx
  src/page/archiving/index/component/TotalDocument/TotalDocument.style.ts
  src/page/archiving/index/component/TotalDocument/TotalDocument.tsx
  src/shared/component/LeftSidebar/LeftSidebar.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/ClickStick/ClickStick.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.style.ts
Labels: ♻️Refactor, 🍭규홍

#188 [Fix] 타임라인 블록 생성 이슈 해결
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DaySection/DaySection.style.ts
  src/page/archiving/index/component/DaySection/DaySection.tsx
  src/page/archiving/index/util/block.ts
Labels: 💫다은, 🐛Bug

#196 [Docs] s3 cloudfront ci cd workflow
  .github/workflows/automatic-aws-deployment.yml
  .github/workflows/chromatic.yml
Labels: ⭐️주용, 📄Docs

#201 [Refactor] Zustand Selector and Export Logic refactoring
  src/common/component/Header/Header.tsx
  src/common/component/Modal/Modal.tsx
  src/common/component/ToastContainer/ToastProvider.tsx
  src/page/archiving/createTimeBlock/component/Upload/UploadModal.tsx
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DocumentItem/DocumentItem.tsx
  src/page/archiving/index/component/SelectedBlock/SelectedBlock.tsx
  src/page/archiving/index/component/TotalDocument/TotalDocument.tsx
  src/page/login/index/hook/useLoginMutation.ts
  src/page/login/password/auth/PasswordAuthPage.tsx
  src/page/login/password/auth/hook/useResendMailMutation.ts
  src/page/login/password/reset/hook/useResetPasswordMutation.ts
  src/page/signUp/index/TermPage.tsx
  src/page/signUp/info/component/InfoForm/InfoForm.tsx
  src/page/signUp/info/hook/api/useSendMailMutation.ts
  src/page/signUp/info/hook/api/useSignupMutation.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/Login/Login.tsx
  src/shared/hook/api/useVerifyCodeMutation.ts
  src/shared/hook/common/useLogout.ts
  src/shared/store/auth.ts
  src/shared/store/team.ts
  src/shared/store/toast.ts
  src/story/common/Toast.stories.tsx
Labels: ⭐️주용, ♻️Refactor

#207 [Refactor] Refresh Token 쿠키 관리 로직 + teamId 저장 로직 리팩토링
  .github/workflows/automatic-aws-deployment.yml
  src/common/hook/useErrorBoundary.ts
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/SelectedBlock/SelectedBlock.tsx
  src/page/archiving/index/component/TotalDocument/TotalDocument.tsx
  src/page/login/index/hook/useLoginMutation.ts
  src/shared/api/auth/reissue/index.ts
  src/shared/api/instance.ts
  src/shared/api/interceptor.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/hook/common/useLogout.ts
  src/shared/hook/common/useTokenError.ts
  src/shared/page/errorPage/ErrorPage.tsx
Labels: ⭐️주용, ♻️Refactor

#198 [Refactor] 환경설정 메뉴 리팩토링(css)
  src/shared/component/LeftSidebar/LeftSidebarItem/SettingMenu/SettingMenu.style.ts
Labels: ♻️Refactor, 🤍보운

#208 [Refactor] 아카이빙 페이지 리팩토링
  src/page/archiving/index/ArchivingPage.style.ts
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DaySection/DaySection.tsx
  src/page/archiving/index/component/TimeBlock/TimeBlock.style.ts
  src/page/archiving/index/component/TimeBlock/TimeBlock.tsx
  src/page/archiving/index/component/YearHeader/YearHeader.tsx
  src/page/archiving/index/hook/common/useDate.ts
  src/story/page/archiving/DaySection.stories.tsx
Labels: ♻️Refactor, 💫다은

#204 [Refactor] 컴포넌트, 변수명 리펙토링
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DocumentBar/DocumentBar.tsx
  src/page/archiving/index/component/DocumentBarTab/DocumentBarTab.style.ts
  src/page/archiving/index/component/DocumentBarTab/DocumentBarTab.tsx
  src/page/archiving/index/component/DocumentItem/DocumentItem.style.ts
  src/page/archiving/index/component/DocumentItem/DocumentItem.tsx
  src/page/archiving/index/component/SelectedBlock/SelectedBlock.tsx
  src/page/archiving/index/component/TotalDocument/TotalDocument.tsx
  src/page/archiving/index/hook/api/useBlockInfoQuery.ts
  src/page/archiving/index/util/document.ts
  src/shared/component/LeftSidebar/LeftSidebar.style.ts
  src/shared/component/LeftSidebar/LeftSidebar.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/ClickStick/ClickStick.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarItem.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarMenuItem.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/LeftSidebarMenuItem.tsx
  src/shared/component/LeftSidebar/LeftSidebarItem/PageIndicatorStick/PageIndicatorStick.style.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/PageIndicatorStick/PageIndicatorStick.tsx
  src/story/page/archiving/DocumentBar/DocumentItem.stories.tsx
  src/story/shared/LeftSidebarItem.stories.tsx
Labels: ♻️Refactor, 🍭규홍

#210 [Fix] 연도가 다른 타임 블록 배치
  package.json
  pnpm-lock.yaml
  src/page/archiving/index/ArchivingPage.tsx
  src/page/archiving/index/component/DaySection/DaySection.tsx
  src/page/archiving/index/component/TimeBlock/TimeBlock.tsx
  src/page/archiving/index/hook/common/useDate.ts
  src/page/archiving/index/util/block.ts
Labels: 💫다은, 🐛Bug

#214 [Feature] Sentry 도입, 커스텀 에러 HTTPError 객체 생성을 통한 에러 이벤트에 대한 분리
  .eslintrc.cjs
  .gitignore
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/common/component/ErrorBoundary/ErrorBoundary.tsx
  src/main.tsx
  src/mock/handler/index.ts
  src/shared/api/HTTPError.ts
  src/shared/api/instance.ts
  src/shared/api/interceptor.ts
  src/shared/component/LeftSidebar/LeftSidebarItem/SettingMenu/SettingMenu.tsx
  src/shared/constant/api.ts
  src/shared/hook/common/useTokenError.ts
  vite.config.ts
Labels: ⭐️주용, ✨Feature

#203 [Feature] 회원가입 Form에 폼 상태관리 Custom hook 도입
  .prettierrc
  src/common/hook/index.ts
  src/common/hook/useDebounce.ts
  src/common/hook/useError.ts
  src/page/archiving/index/component/TotalDocument/TotalDocument.tsx
  src/page/signUp/info/InfoFormPage.tsx
  src/page/signUp/info/component/InfoForm/InfoForm.tsx
  src/page/signUp/info/component/PasswordForm/PasswordForm.tsx
  src/page/signUp/info/hook/common/useDateInput.ts
  src/page/signUp/info/hook/common/useInfoForm.ts
  src/page/signUp/info/hook/common/usePasswordForm.ts
  src/shared/constant/form.ts
  src/shared/util/typeGuard.ts
Labels: ⭐️주용, ✨Feature

#215 [Refactor] useOutsideClick 순수성 유지
  src/common/hook/useOutsideClick.ts
  src/shared/component/createWorkSpace/category/WorkSpaceCategory.tsx
Labels: ♻️Refactor, 🍭규홍
