Repository Team-Tiki/tiki-client, pull requests merged in 2025-01, with the labels that each got.

#364 [Feat] 팀 내 권한 get api 구현 및 그에 따른 뷰 작업
  apps/client/src/page/workspaceSetting/component/InfoSetting.tsx
  apps/client/src/page/workspaceSetting/component/ProfileSetting.tsx
  apps/client/src/page/workspaceSetting/constant/index.ts
  apps/client/src/page/workspaceSetting/hook/api/queries.ts
  apps/client/src/page/workspaceSetting/index.tsx
  apps/client/src/page/workspaceSetting/type/index.ts
  apps/client/src/shared/__generated__/schema.d.ts
  packages/ui/src/Select/Select.tsx
Labels: ✨Feature, 🍭규홍

#368 [Feat] note 목록 조회 api + dashboard에 적용
  apps/client/package.json
  apps/client/src/page/dashboard/component/Handover/HandoverSection.tsx
  apps/client/src/page/dashboard/component/Handover/ListItem/ListItem.tsx
  apps/client/src/page/handover/hook/api/queries.ts
  apps/client/src/story/page/dashboard/component/ListItem.stories.tsx
Labels: ✨Feature, 🤍보운

#373 [Feat] 인수인계 노트 리스트 보여주기 api 연결 및 뷰 마무리
  apps/client/src/page/handover/HandoverPage.tsx
  apps/client/src/page/handover/component/NoteItem/NoteItem.style.ts
  apps/client/src/page/handover/component/NoteItem/NoteItem.tsx
  apps/client/src/page/handover/constant/index.ts
  apps/client/src/page/handover/constant/noteList.ts
  apps/client/src/page/handover/type/index.ts
  apps/client/src/story/page/handover/NoteItem.stories.tsx
Labels: ✨Feature, 🍭규홍

#383 [Fix] 타임블록 타입 이슈 해결
  apps/client/src/page/archiving/index/ArchivingPage.tsx
  apps/client/src/page/archiving/index/component/DocumentBar/Selected/Selected.tsx
  apps/client/src/page/archiving/index/component/TimeBlockBar/BlockInfo/BlockInfo.tsx
  apps/client/src/page/archiving/index/component/TimeLine/index.tsx
  apps/client/src/page/archiving/index/hook/api/useGetTimeBlockQuery.ts
  apps/client/src/page/archiving/index/hook/common/useInteractTimeline.ts
  apps/client/src/page/archiving/index/type/blockType.ts
  apps/client/src/shared/api/time-blocks/team/timeline/index.ts
  apps/client/src/shared/store/drawer.ts
Labels: 🫧다은, 🐛Bug

#380 [Feat] Caution modal 구현
  apps/client/src/page/handover/note/component/CreateNote/CreateNote.tsx
  apps/client/src/shared/component/CautionModal/CautionModal.style.ts
  apps/client/src/shared/component/CautionModal/CautionModal.tsx
  apps/client/src/shared/component/DeletedModal/DeletedModal.tsx
  apps/client/src/shared/component/Modal/Footer/ModalFooter.tsx
  apps/client/src/shared/component/Modal/Header/ModalHeader.tsx
  apps/client/src/shared/component/Modal/ModalFunnel.tsx
  apps/client/src/shared/constant/index.ts
  apps/client/src/shared/constant/modal.tsx
  apps/client/src/shared/store/modal.tsx
  packages/icon/assets/svg/ic_caution.svg
  packages/icon/assets/svg/ic_caution_toast.svg
  packages/icon/index.ts
  packages/icon/src/IcCaution.tsx
  packages/icon/src/IcCautionToast.tsx
  packages/ui/src/Toast/Toast.tsx
Labels: 🫧다은, ✨Feature

#391 [Fix] 파일 업로드시 용량 포맷팅
  apps/client/src/page/archiving/index/component/TimeBlockModal/component/UploadModal/File/AppendFile/AppendFile.tsx
  apps/client/src/shared/constant/modal.tsx
  apps/client/src/shared/util/file.ts
  packages/icon/assets/svg/ic_caution.svg
  packages/icon/assets/svg/ic_caution_toast.svg
  packages/icon/assets/svg/ic_error.svg
  packages/icon/index.ts
  packages/icon/src/IcCaution.tsx
  packages/icon/src/IcCautionToast.tsx
  packages/icon/src/IcError.tsx
  packages/ui/src/Toast/Toast.tsx
Labels: 🫧다은, ✨Feature

#378 [Feat] 워크스페이스 삭제 api 연결 및 모달 구현
  apps/client/src/page/workspaceSetting/index.tsx
  apps/client/src/shared/api/queryClient.ts
  apps/client/src/shared/component/DeletedModal/DeletedModal.style.ts
  apps/client/src/shared/component/DeletedModal/DeletedModal.tsx
  apps/client/src/shared/component/InviteModal/InviteModal.tsx
  apps/client/src/shared/component/Modal/Body/ModalBody.style.ts
  apps/client/src/shared/component/Modal/Footer/ModalFooter.tsx
  apps/client/src/shared/component/Modal/ModalFunnel.tsx
  apps/client/src/shared/component/SideNavBar/SideNavBar.tsx
  apps/client/src/shared/component/WorkSpaceModal/category/WorkSpaceCategory.tsx
  apps/client/src/shared/component/WorkSpaceModal/complete/WorkSpaceComplete.tsx
  apps/client/src/shared/component/WorkSpaceModal/image/WorkSpaceImage.tsx
  apps/client/src/shared/component/WorkSpaceModal/name/WorkSpaceName.tsx
  apps/client/src/shared/constant/index.ts
  apps/client/src/shared/hook/api/useClubInfoQuery.ts
  apps/client/src/shared/hook/api/usePostTeamMutation.ts
  apps/client/src/shared/hook/common/useWorkSpaceContext.tsx
  apps/client/src/shared/store/modal.tsx
  apps/client/src/story/shared/DeleteModal.stories.tsx
  packages/ui/src/Button/Button.style.ts
  packages/ui/src/Button/Button.tsx
  packages/ui/src/Modal/Modal.style.ts
  packages/ui/src/Modal/Modal.tsx
  packages/ui/src/theme.ts
Labels: 🫧다은, ✨Feature

#401 [FIX] UI package resolve alias 추가
  apps/client/vite.config.ts
Labels: ⭐️주용, 🐛Bug

#403 [Fix] Vite config Icon deps, alias 추가
  apps/client/vite.config.ts
Labels: ⭐️주용, ✨Feature, 🐛Bug

#405 [Chore] rollup commonjs plugin 추가
  apps/client/package.json
  apps/client/vite.config.ts
  pnpm-lock.yaml
Labels: ⭐️주용, 🐛Bug, 🚀Deployment

#407 [Docs] QA용 버셀 프로덕션 배포를 위한 vercel json 추가
  apps/client/vercel.json
Labels: ⭐️주용, 📄Docs, 🚀Deployment

#374 [Feat] 휴지통 뷰 영구삭제 및 복구 api 연결
  apps/client/src/page/deleted/index.tsx
  apps/client/src/page/handover/note/NotePage.tsx
  apps/client/src/shared/__generated__/schema.d.ts
Labels: ✨Feature, 🤍보운

#384 [Feat] 초대 페이지 퍼블리싱
  apps/client/src/common/router/Router.tsx
  apps/client/src/common/router/lazy.ts
  apps/client/src/page/invite/index.styles.ts
  apps/client/src/page/invite/index.tsx
  apps/client/src/shared/component/Header/Header.tsx
  apps/client/src/shared/constant/path.ts
Labels: ✨Feature, 🤍보운

#411 [Docs] Vite config rollupOptions 제외 불필요 속성 삭제
  apps/client/vite.config.ts
Labels: ⭐️주용, 📄Docs

#389 [Feat] 파일/폴더 삭제 api
  apps/client/src/page/drive/component/FileListItem/FileListItem.tsx
  apps/client/src/page/drive/component/FileListItem/FolderListItem.tsx
  apps/client/src/page/drive/hook/common/useSelectDocuments.ts
  apps/client/src/page/drive/index.tsx
  apps/client/src/shared/component/FileGrid/FileGrid.tsx
  apps/client/src/shared/component/FileGrid/FolderGrid.tsx
  apps/client/src/shared/component/FileGrid/index.style.ts
Labels: 🫧다은, ✨Feature

#392 [Feat] 타임블록 활동 태그 모달 api
  apps/client/src/common/router/lazy.ts
  apps/client/src/page/handoverNote/component/CreateNote/CreateNote.tsx
  apps/client/src/page/handoverNote/component/CreateNote/Custom/CreateCustomNote.tsx
  apps/client/src/page/handoverNote/component/CreateNote/NoteDetail/CreateNoteDetail.tsx
  apps/client/src/page/handoverNote/component/CreateNote/Template/CreateTemplateNote.tsx
  apps/client/src/page/handoverNote/component/Custom/Custom.style.ts
  apps/client/src/page/handoverNote/component/Custom/Custom.tsx
  apps/client/src/page/handoverNote/component/File/File.style.ts
  apps/client/src/page/handoverNote/component/File/File.tsx
  apps/client/src/page/handoverNote/component/NoteDetail/NoteDetail.style.ts
  apps/client/src/page/handoverNote/component/NoteDetail/NoteDetail.tsx
  apps/client/src/page/handoverNote/component/Template/Template.style.ts
  apps/client/src/page/handoverNote/component/Template/Template.tsx
  apps/client/src/page/handoverNote/constants/tag.ts
  apps/client/src/page/handoverNote/constants/template.ts
  apps/client/src/page/handoverNote/hooks/useFile.ts
  apps/client/src/page/handoverNote/index.style.ts
  apps/client/src/page/handoverNote/index.tsx
  apps/client/src/page/handoverNote/type/note.ts
  apps/client/src/page/handoverNote/util/date.ts
  apps/client/src/shared/component/ActivityTagModal/ActivityTagItem/ActivityTagItem.tsx
  apps/client/src/shared/component/ActivityTagModal/ActivityTagModal.tsx
  apps/client/src/shared/constant/modal.tsx
  apps/client/src/shared/util/date.ts
Labels: 🫧다은, ✨Feature

#394 [Feat] 파일 연동 모달 구현
  apps/client/src/page/archiving/index/component/TimeBlockModal/component/UploadModal/File/AppendFile/AppendFile.tsx
  apps/client/src/page/handoverNote/component/CreateNote/Template/CreateTemplateNote.tsx
  apps/client/src/shared/component/FileImportModal/FileImportModal.style.ts
  apps/client/src/shared/component/FileImportModal/FileImportModal.tsx
  apps/client/src/shared/component/Modal/Footer/ModalFooter.tsx
  apps/client/src/shared/component/Modal/ModalFunnel.tsx
  apps/client/src/shared/component/UploadedFileItem/UploadedFileItem.style.ts
  apps/client/src/shared/component/UploadedFileItem/UploadedFileItem.tsx
  apps/client/src/shared/constant/index.ts
  apps/client/src/shared/constant/modal.tsx
  apps/client/src/shared/store/modal.tsx
Labels: 🫧다은, ✨Feature

#421 [Feat] 휴지통 뷰 삭제 경고 모달 연결
  apps/client/src/page/deleted/index.tsx
  apps/client/src/page/drive/index.tsx
  apps/client/src/shared/component/Modal/ModalFunnel.tsx
  apps/client/src/shared/component/TimeBlockModal/component/BlockInfoModal/BlockInfoModal.tsx
  apps/client/src/shared/component/TimeBlockModal/component/Box/BlockBox.tsx
  apps/client/src/shared/component/TimeBlockModal/component/CategoryModal/Category/Category.style.ts
  apps/client/src/shared/component/TimeBlockModal/component/CategoryModal/Category/Category.tsx
  apps/client/src/shared/component/TimeBlockModal/component/CategoryModal/CategoryModal.style.ts
  apps/client/src/shared/component/TimeBlockModal/component/CategoryModal/CategoryModal.tsx
  apps/client/src/shared/component/TimeBlockModal/component/SelectedFileModal/FileItem/FileItem.style.ts
  apps/client/src/shared/component/TimeBlockModal/component/SelectedFileModal/FileItem/FileItem.tsx
  apps/client/src/shared/component/TimeBlockModal/component/SelectedFileModal/SelectedFileModal.style.ts
  apps/client/src/shared/component/TimeBlockModal/component/SelectedFileModal/SelectedFileModal.tsx
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/File/AppendFile/AppendFile.style.ts
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/File/AppendFile/AppendFile.tsx
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/File/BrowseFile/BrowseFile.tsx
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/File/BrowseFile/File/BrowseFileItem.style.ts
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/File/BrowseFile/File/BrowseFileItem.tsx
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/File/BrowseFile/FileHeader/BrowseFileHeader.style.ts
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/File/BrowseFile/FileHeader/BrowseFileHeader.tsx
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/UploadModal.style.ts
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/UploadModal.tsx
  apps/client/src/shared/component/TimeBlockModal/constant/category.tsx
  apps/client/src/shared/component/TimeBlockModal/constant/color.ts
  apps/client/src/shared/component/TimeBlockModal/constant/error.ts
  apps/client/src/shared/component/TimeBlockModal/constant/iconBlock.tsx
  apps/client/src/shared/component/TimeBlockModal/hook/api/useDeleteFileMutation.ts
  apps/client/src/shared/component/TimeBlockModal/hook/api/usePostTimeBlockMutation.ts
  apps/client/src/shared/component/TimeBlockModal/hook/api/usePutUploadMutation.ts
  apps/client/src/shared/component/TimeBlockModal/hook/common/useBlockName.ts
  apps/client/src/shared/component/TimeBlockModal/hook/common/useFile.tsx
  apps/client/src/shared/component/TimeBlockModal/index.tsx
  apps/client/src/shared/component/TimeBlockModal/type/block.ts
  apps/client/src/shared/component/TimeBlockModal/type/blockType.ts
  apps/client/src/shared/component/TimeBlockModal/util/color.ts
  apps/client/src/shared/component/TimeBlockModal/util/date.ts
  apps/client/src/shared/component/WorkSpaceModal/image/hook/useImageUpload.tsx
  apps/client/src/shared/constant/index.ts
  apps/client/src/shared/constant/modal.tsx
  apps/client/src/shared/hook/common/useBlockContext.tsx
Labels: 🫧다은, ✨Feature

#422 [Feat] 파일 다운로드 핸들러 연결
  apps/client/src/page/archiving/index/component/DocumentBar/Item/Item.tsx
  apps/client/src/page/drive/component/FileListItem/FileListItem.tsx
  apps/client/src/page/drive/component/FileListItem/FolderListItem.tsx
  apps/client/src/shared/component/FileGrid/FileGrid.tsx
  apps/client/src/shared/util/document.ts
Labels: 🫧다은, ✨Feature

#425 [Feat] mainadd 컴포넌트 제작 및 스타일 수정
  apps/client/src/page/dashboard/DashboardPage.style.ts
  apps/client/src/page/dashboard/component/File/FileSection.tsx
  apps/client/src/page/dashboard/component/Handover/HandoverSection.style.ts
  apps/client/src/page/dashboard/component/Handover/HandoverSection.tsx
  apps/client/src/page/dashboard/component/Handover/ListItem/ListItem.style.ts
  apps/client/src/page/dashboard/component/ItemAdder/ItemAdder.styles.ts
  apps/client/src/page/dashboard/component/ItemAdder/ItemAdder.tsx
  apps/client/src/page/dashboard/component/Timeline/Timeline/Timeline.tsx
  apps/client/src/shared/component/FileGrid/index.style.ts
  packages/icon/assets/svg/ic_main_add.svg
  packages/icon/index.ts
  packages/icon/src/IcMainAdd.tsx
Labels: ✨Feature, 🤍보운

#426 [Feat] 초대페이지 api 연결 및 경로 조정
  apps/client/src/page/dashboard/DashboardPage.tsx
  apps/client/src/page/invite/hook/common/useInvitationInfo.ts
  apps/client/src/page/invite/hook/queries.ts
  apps/client/src/page/invite/index.tsx
  apps/client/src/page/invite/type.ts
  apps/client/src/shared/constant/api.ts
Labels: ✨Feature, 🤍보운

#388 [Feat] 인수인계 노트 목록 삭제 api 연결 및 뷰 마무리
  apps/client/src/page/handover/HandoverPage.tsx
  apps/client/src/page/handover/component/NoteItem/NoteItem.tsx
  apps/client/src/page/handover/constant/index.ts
  apps/client/src/page/handover/hook/api/queries.ts
  apps/client/src/page/handover/type/index.ts
  apps/client/src/shared/hook/common/useIntersect.ts
  apps/client/src/story/page/handover/NoteItem.stories.tsx
  packages/icon/assets/svg/ic_caution.svg
  packages/icon/assets/svg/ic_caution_toast.svg
  packages/icon/index.ts
  packages/icon/src/IcCautionToast.tsx
  packages/ui/src/Toast/Toast.tsx
Labels: ✨Feature, 🍭규홍

#428 [Feat] 파일 임포트 모달 handoverNote와 연결
  apps/client/src/page/handoverNote/component/CreateNote/CreateNote.tsx
  apps/client/src/page/handoverNote/component/CreateNote/Custom/CreateCustomNote.tsx
  apps/client/src/page/handoverNote/component/CreateNote/Template/CreateTemplateNote.tsx
  apps/client/src/page/handoverNote/component/Custom/Custom.tsx
  apps/client/src/page/handoverNote/component/File/File.tsx
  apps/client/src/page/handoverNote/component/Template/Template.tsx
  apps/client/src/shared/component/ActivityTagModal/ActivityTagModal.style.ts
  apps/client/src/shared/component/ActivityTagModal/ActivityTagModal.tsx
  apps/client/src/shared/component/FileImportModal/FileImportModal.style.ts
  apps/client/src/shared/component/FileImportModal/FileImportModal.tsx
  apps/client/src/shared/store/modal.tsx
Labels: 🫧다은, ✨Feature

#432 [Fix] QA 배포본 로그인 에러 해결
  apps/client/src/page/dashboard/component/File/FileSection.tsx
  apps/client/src/page/dashboard/component/Handover/HandoverSection.style.ts
  apps/client/src/page/dashboard/component/Handover/HandoverSection.tsx
  apps/client/src/page/dashboard/component/Timeline/Timeline/Timeline.tsx
  apps/client/src/page/dashboard/component/Timeline/index.tsx
  apps/client/src/page/drive/hook/api/queries.ts
  apps/client/src/page/login/index/hook/useLoginMutation.ts
  apps/client/src/shared/component/SideNavBar/SideNavBar.tsx
  apps/client/src/shared/hook/common/useInitializeTeamId.tsx
  apps/client/src/shared/store/team.ts
Labels: ⭐️주용, 🐛Bug

#437 [Refactor] Dropdown 상태 관리 로직 리팩토링, UI 반영
  apps/client/src/page/drive/index.tsx
  apps/client/src/page/handover/HandoverPage.tsx
  apps/client/src/page/signUp/info/UnivFormPage.tsx
  apps/client/src/page/signUp/info/hook/common/useUnivForm.ts
  apps/client/src/page/workspaceSetting/component/InfoSetting.tsx
  apps/client/src/shared/component/ActivityTagModal/ActivityTagModal.style.ts
  apps/client/src/shared/component/ActivityTagModal/ActivityTagModal.tsx
  apps/client/src/shared/component/FileImportModal/FileImportModal.style.ts
  apps/client/src/shared/component/FileImportModal/FileImportModal.tsx
  apps/client/src/shared/component/WorkSpaceModal/category/WorkSpaceCategory.tsx
  apps/client/src/story/common/Select.stories.tsx
  packages/ui/src/Dropdown/Dropdown.style.ts
  packages/ui/src/Dropdown/Dropdown.tsx
  packages/ui/src/Dropdown/DropdownItem.tsx
  packages/ui/src/Dropdown/DropdownList.tsx
  packages/ui/src/Dropdown/DropdownTrigger.tsx
  packages/ui/src/Dropdown/context.ts
  packages/ui/src/Select/Select.style.ts
  packages/ui/src/Select/Select.tsx
Labels: ⭐️주용, ♻️Refactor

#441 [Feat] 헤더 미반영사항 기능 구현
  apps/client/src/page/dashboard/DashboardPage.tsx
  apps/client/src/page/handoverNote/component/CreateNote/NoteDetail/CreateNoteDetail.tsx
  apps/client/src/page/invite/hook/common/useInvitationInfo.ts
  apps/client/src/page/invite/index.tsx
  apps/client/src/page/landing/LandingPage.tsx
  apps/client/src/page/login/index/hook/useLoginMutation.ts
  apps/client/src/page/workspaceSetting/index.tsx
  apps/client/src/shared/api/interceptor.ts
  apps/client/src/shared/api/middleware.ts
  apps/client/src/shared/component/Header/Header.style.ts
  apps/client/src/shared/component/Header/Header.tsx
  apps/client/src/shared/component/Header/InviteButton.tsx
  apps/client/src/shared/component/Header/SettingButton.tsx
  apps/client/src/shared/component/Login/Login.tsx
  apps/client/src/shared/component/SideNavBar/SideNavBar.tsx
  apps/client/src/shared/constant/api.ts
  apps/client/src/shared/hook/common/useInitializeTeamId.tsx
  apps/client/src/shared/store/team.ts
Labels: ⭐️주용, ✨Feature

#438 [Feat] 대시보드 뷰 1차 기능 QA
  apps/client/src/page/dashboard/component/File/FileSection.tsx
  apps/client/src/page/dashboard/component/Handover/HandoverSection.tsx
  apps/client/src/shared/component/Header/AlarmButton.tsx
  apps/client/src/shared/component/Header/Header.tsx
  apps/client/src/shared/component/Header/SettingButton.tsx
  apps/client/src/shared/hook/common/useCurrentDate.ts
Labels: ♻️Refactor, ✨Feature, 🤍보운

#442 [Feat] QA 해결 2
  .prettierignore
  apps/client/src/page/archiving/index/component/TimeBlockBar/UploadedDocumentss/FileItem/FileItem.tsx
  apps/client/src/page/drive/index.tsx
  apps/client/src/page/login/password/auth/PasswordAuthPage.tsx
  apps/client/src/page/login/password/auth/hook/api/useResendMailMutation.ts
  apps/client/src/page/login/password/reset/PasswordResetPage.tsx
  apps/client/src/page/login/password/reset/hook/api/useResetPasswordMutation.ts
  apps/client/src/page/workspaceSetting/index.tsx
  apps/client/src/shared/component/DeletedModal/DeletedModal.style.ts
  apps/client/src/shared/component/DeletedModal/DeletedModal.tsx
  apps/client/src/shared/component/FileImportModal/FileImportModal.tsx
  apps/client/src/shared/component/ImageImportModal/ImageImportModal.style.ts
  apps/client/src/shared/component/ImageImportModal/ImageImportModal.tsx
  apps/client/src/shared/component/InviteModal/InviteModal.style.ts
  apps/client/src/shared/component/InviteModal/InviteModal.tsx
  apps/client/src/shared/component/InviteModal/Member/MemberItem.tsx
  apps/client/src/shared/component/MemberTagModal/MemberTagItem/MemberTagItem.tsx
  apps/client/src/shared/component/MemberTagModal/MemberTagModal.tsx
  apps/client/src/shared/component/Modal/Footer/ModalFooter.tsx
  apps/client/src/shared/component/Modal/Header/ModalHeader.tsx
  apps/client/src/shared/component/Modal/ModalFunnel.tsx
  apps/client/src/shared/component/NewFileImportModal/NewFileImportModal.style.ts
  apps/client/src/shared/component/NewFileImportModal/NewFileImportModal.tsx
  apps/client/src/shared/component/TimeBlockModal/component/BlockInfoModal/BlockInfoModal.tsx
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/BrowseFile/BrowseFile.tsx
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/BrowseFile/BrowseFileItem.style.ts
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/BrowseFile/BrowseFileItem.tsx
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/BrowseFile/FileHeader/BrowseFileHeader.style.ts
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/BrowseFile/FileHeader/BrowseFileHeader.tsx
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/File/AppendFile/AppendFile.style.ts
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/File/AppendFile/AppendFile.tsx
  apps/client/src/shared/component/TimeBlockModal/component/UploadModal/UploadModal.tsx
  apps/client/src/shared/component/TimeBlockModal/hook/common/useFile.tsx
  apps/client/src/shared/component/UploadedFileItem/UploadedFileItem.style.ts
  apps/client/src/shared/component/UploadedFileItem/UploadedFileItem.tsx
  apps/client/src/shared/component/WorkSpaceModal/hook/common/useImageUpload.tsx
  apps/client/src/shared/component/WorkSpaceModal/image/WorkSpaceImage.tsx
  apps/client/src/shared/component/WorkSpaceModal/invite/Member/MemberItem.style.ts
  apps/client/src/shared/constant/index.ts
  apps/client/src/shared/constant/modal.tsx
  apps/client/src/shared/store/modal.tsx
  apps/client/src/shared/type/modal.ts
  apps/client/src/shared/util/document.ts
  apps/client/src/shared/util/file.ts
  packages/ui/src/DatePicker/Trigger/DatePickerTrigger.tsx
  packages/ui/src/Modal/Modal.style.ts
  packages/ui/src/Modal/Modal.tsx
  packages/ui/src/types.ts
Labels: 🫧다은, ✨Feature
