Repository Team-Tiki/tiki-client, pull requests merged in 2025-03, with the labels that each got.

#493 [Fix] 드라이브 페이지 QA
  apps/client/src/page/drive/component/FileListHeader/FileListHeader.style.ts
  apps/client/src/page/drive/component/FileListItem/FileListItem.style.ts
  apps/client/src/page/drive/component/FileListItem/FileListItem.tsx
  apps/client/src/page/drive/component/FileListItem/FolderListItem.tsx
  apps/client/src/page/drive/index.style.ts
  apps/client/src/page/drive/index.tsx
  apps/client/src/shared/component/FileGrid/FileGrid.tsx
  apps/client/src/shared/component/FileGrid/index.style.ts
  apps/client/src/shared/util/file.ts
  apps/client/src/story/page/drive/FileListItem.stories.tsx
  packages/utils/src/hooks/useDeferedSearchFilter.ts
Labels: ⭐️주용, 🐛Bug

#487 [Fix] 타임라인 QA 해결
  apps/client/src/page/archiving/index/ArchivingPage.style.ts
  apps/client/src/page/archiving/index/component/TimeBlockBar/UploadedDocuments/FileItem/FileItem.tsx
  apps/client/src/page/archiving/index/component/TimeLine/Day/Day.style.ts
  apps/client/src/page/archiving/index/component/TimeLine/Day/Day.tsx
  apps/client/src/page/archiving/index/component/TimeLine/TimeLineHeader/TimeLineHeader.style.ts
  apps/client/src/page/archiving/index/component/TimeLine/TimeLineHeader/TimeLineHeader.tsx
  apps/client/src/page/archiving/index/component/TimeLine/index.tsx
  apps/client/src/page/dashboard/component/Timeline/Timeline/Timeline.tsx
  apps/client/src/page/handover/HandoverPage.tsx
  apps/client/src/shared/component/ActivityTagModal/ActivityTagModal.tsx
  apps/client/src/shared/component/BrowseFileModal/BrowseFileModal.tsx
  apps/client/src/shared/component/FileImportModal/FileImportModal.tsx
  apps/client/src/shared/component/Modal/ModalFunnel.tsx
  apps/client/src/shared/component/NewFileUploadModal/FileUploadContainer/FileUploadContainer.tsx
  apps/client/src/shared/component/NewFileUploadModal/NewFileImportModal.style.ts
  apps/client/src/shared/component/NewFileUploadModal/NewFileUploadModal.tsx
  apps/client/src/shared/component/SelectedFilesModal/SelectedFilesModal.tsx
  apps/client/src/shared/component/SideNavBar/UserMenu.tsx
  apps/client/src/shared/component/TimeBlockModal/SelectedFileModal.tsx
  apps/client/src/shared/component/TimeBlockModal/UploadModal.tsx
  apps/client/src/shared/component/TimeBlockModal/component/BrowseFile/BrowseFileModal.tsx
  apps/client/src/shared/component/TimeBlockModal/hook/api/useDeleteFileMutation.ts
  apps/client/src/shared/component/WorkSpaceModal/hook/common/useImageUpload.tsx
  apps/client/src/shared/constant/index.ts
  apps/client/src/shared/constant/toast.ts
  apps/client/src/shared/hook/api/useGetFileQuery.ts
  apps/client/src/shared/hook/common/useTimeBlockUploadFlow.tsx
  apps/client/src/shared/util/file.ts
Labels: 🫧다은, ✨Feature, 🐛Bug

#496 [Fix] 인수인계 노트 QA 해결
  .gitattributes
  .gitignore
  apps/client/src/page/handover/component/CreateNote/CreateCustomNote.tsx
  apps/client/src/page/handover/component/CreateNote/CreateNoteDetail.tsx
  apps/client/src/page/handover/component/CreateNote/CreateTemplateNote.tsx
  apps/client/src/page/handover/component/CreateNote/index.tsx
  apps/client/src/page/handover/constant/index.ts
  apps/client/src/page/handover/hook/common/useNoteInfoForm.ts
  apps/client/src/page/handoverNote/component/Custom.tsx
  apps/client/src/page/handoverNote/component/File/File.tsx
  apps/client/src/page/handoverNote/component/NoteInfo.tsx
  apps/client/src/page/handoverNote/component/Template.tsx
  apps/client/src/page/handoverNote/component/style.ts
  apps/client/src/page/handoverNote/constants/noteConfig.ts
  apps/client/src/page/handoverNote/hook/api/queries.ts
  apps/client/src/page/handoverNote/hook/common/useFile.ts
  apps/client/src/page/handoverNote/hook/common/useNoteInfoForm.ts
  apps/client/src/page/handoverNote/index.tsx
  apps/client/src/page/handoverNote/type/note.ts
  apps/client/src/shared/__generated__/schema.d.ts
  apps/client/src/shared/__generated__/schema.json
  apps/client/src/shared/component/ActivityTagModal/ActivityTagModal.style.ts
  apps/client/src/shared/component/ActivityTagModal/ActivityTagModal.tsx
  apps/client/src/shared/component/FileImportModal/FileImportModal.tsx
  apps/client/src/shared/component/Modal/Footer/ModalFooter.tsx
  apps/client/src/shared/store/modal.tsx
  apps/client/src/shared/type/modal.ts
Labels: 🫧다은, 🐛Bug

#499 [Fix] 초대 페이지 및 대시보드 페이지 QA
  apps/client/src/page/dashboard/DashboardPage.tsx
  apps/client/src/page/drive/util/convertDataUnit.ts
  apps/client/src/page/invite/constant/index.ts
  apps/client/src/page/invite/index.tsx
  apps/client/src/page/workspaceSetting/component/WorkspaceDelete.tsx
  apps/client/src/shared/component/Header/Header.tsx
Labels: ♻️Refactor, ✨Feature, 🤍보운

#502 [Fix]대시보드페이지의 파일섹션 QA
  apps/client/src/page/dashboard/component/File/FileSection.tsx
  apps/client/src/shared/component/FileGrid/FileGrid.tsx
  apps/client/src/shared/component/FileGrid/FolderGrid.tsx
  apps/client/src/shared/component/FileGrid/index.style.ts
Labels: ✨Feature, 🤍보운

#500 [Refactor] qa 해결
  apps/client/src/page/archiving/index/component/TimeBlockBar/DeleteTimeBlockButton/DeleteTimeBlockButton.tsx
  apps/client/src/page/archiving/index/component/TimeBlockBar/TimeBlockBar.tsx
  apps/client/src/page/archiving/index/component/TimeBlockBar/UploadedDocuments/index.tsx
  apps/client/src/page/handover/HandoverPage.tsx
  apps/client/src/page/workspaceSetting/component/TeamProfileSetting.tsx
  apps/client/src/page/workspaceSetting/component/WorkspaceDataSubmitButton/WorkspaceDataSubmitButton.tsx
  apps/client/src/page/workspaceSetting/component/WorkspaceDelete.tsx
  apps/client/src/page/workspaceSetting/hook/useWorkspaceData.ts
  apps/client/src/page/workspaceSetting/index.tsx
  apps/client/src/shared/__generated__/schema.d.ts
  apps/client/src/shared/component/NewFileUploadModal/NewFileUploadModal.tsx
  apps/client/src/shared/component/SideNavBar/TeamList.tsx
  apps/client/src/shared/component/WorkSpaceModal/complete/WorkSpaceComplete.tsx
  apps/client/src/shared/component/WorkSpaceModal/hook/common/useImageUpload.tsx
  apps/client/src/shared/constant/toast.ts
  apps/client/src/shared/hook/common/useTimeBlockUploadFlow.tsx
  packages/ui/src/DatePicker/Calendar/Dates/CalendarDates.tsx
  packages/ui/src/DatePicker/index.tsx
  packages/utils/src/hooks/useDatePicker.ts
  packages/utils/src/hooks/useOutsideClick.ts
Labels: ♻️Refactor, 🍭규홍

#503 [Fix] 워크스페이스 모달 이미지 업로드 QA
  apps/client/src/shared/api/external/index.ts
  apps/client/src/shared/api/file/type.ts
  apps/client/src/shared/api/file/upload/index.ts
  apps/client/src/shared/component/Modal/Footer/ModalFooter.tsx
  apps/client/src/shared/component/WorkSpaceModal/category/WorkSpaceCategory.tsx
  apps/client/src/shared/component/WorkSpaceModal/complete/WorkSpaceComplete.tsx
  apps/client/src/shared/component/WorkSpaceModal/hook/common/useImageUpload.tsx
  apps/client/src/shared/component/WorkSpaceModal/image/WorkSpaceImage.tsx
  apps/client/src/shared/component/WorkSpaceModal/name/WorkSpaceName.tsx
  apps/client/src/shared/constant/index.ts
  apps/client/src/shared/constant/modal.tsx
  apps/client/src/shared/hook/common/useWorkSpaceContext.tsx
Labels: 🫧다은, 🐛Bug
