Repository Team-Tiki/tiki-client, pull requests merged in 2025-02, with the labels that each got.

#455 [Feat] 팀원 초대 모달 연결
  apps/client/src/shared/component/Header/InviteButton.tsx
  apps/client/src/shared/component/InviteModal/InviteModal.style.ts
  apps/client/src/shared/component/InviteModal/InviteModal.tsx
  apps/client/src/shared/component/InviteModal/Member/MemberItem.style.ts
  apps/client/src/shared/component/InviteModal/Member/MemberItem.tsx
  apps/client/src/shared/component/Modal/Footer/ModalFooter.tsx
  apps/client/src/shared/component/Modal/ModalFunnel.tsx
  apps/client/src/shared/constant/modal.tsx
Labels: 🫧다은, ✨Feature

#445 [Refactor] 인수인계 노트 목록 qa 해결
  apps/client/src/page/handover/HandoverPage.tsx
  apps/client/src/page/handover/component/NoteItem/NoteItem.style.ts
  apps/client/src/page/handover/component/NoteItem/NoteItem.tsx
  apps/client/src/page/handover/component/NoteListHeader/NoteListHeader.style.ts
  apps/client/src/page/handover/component/NoteListHeader/NoteListHeader.tsx
  packages/ui/src/CheckBox/CheckBox.tsx
  packages/ui/src/Tag/Tag.style.ts
Labels: ♻️Refactor, 🍭규홍

#450 [Refactor] SideNavBar 데이터 중심 컴포넌트 재설계
  apps/client/src/shared/__generated__/schema.d.ts
  apps/client/src/shared/component/SideNavBar/AddWorkspaceButton.tsx
  apps/client/src/shared/component/SideNavBar/Item/Item.tsx
  apps/client/src/shared/component/SideNavBar/Logo.tsx
  apps/client/src/shared/component/SideNavBar/SideNavBar.style.ts
  apps/client/src/shared/component/SideNavBar/SideNavBar.tsx
  apps/client/src/shared/component/SideNavBar/TeamList.tsx
  apps/client/src/shared/component/SideNavBar/UserMenu.tsx
  apps/client/src/shared/component/SideNavBar/index.style.ts
  apps/client/src/story/shared/SideNavBarItem.stories.tsx
  packages/icon/assets/svg/ic_edit_profile.svg
  packages/icon/assets/svg/ic_exit.svg
  packages/icon/generateIcon.ts
  packages/icon/index.ts
  packages/icon/src/IcEditProfile.tsx
  packages/icon/src/IcExit.tsx
  packages/ui/src/Menu/MenuList/MenuList.style.ts
Labels: ⭐️주용, ♻️Refactor

#457 [feat] 휴지통페이지 디자인 QA + 팀용량 api
  apps/client/src/page/deleted/index.tsx
  apps/client/src/page/drive/hook/api/useTeamUsage.ts
  apps/client/src/page/drive/index.style.ts
  apps/client/src/page/drive/index.tsx
  apps/client/src/page/drive/util/convertDataUnit.ts
Labels: ✨Feature, 🤍보운

#470 [Refactor] 타임라인 바 qa
  apps/client/src/common/style/globalStyle.ts
  apps/client/src/page/archiving/index/component/TimeBlockBar/BlockInfo/BlockInfo.tsx
  apps/client/src/page/archiving/index/component/TimeBlockBar/DeleteFileButton/DeleteFileButton.style.ts
  apps/client/src/page/archiving/index/component/TimeBlockBar/DeleteFileButton/DeleteFileButton.tsx
  apps/client/src/page/archiving/index/component/TimeBlockBar/DeleteTimeBlockButton/DeleteTimeBlockButton.css.ts
  apps/client/src/page/archiving/index/component/TimeBlockBar/DeleteTimeBlockButton/DeleteTimeBlockButton.tsx
  apps/client/src/page/archiving/index/component/TimeBlockBar/SubmitButton/SubmitButton.tsx
  apps/client/src/page/archiving/index/component/TimeBlockBar/SubmitButton/quries.ts
  apps/client/src/page/archiving/index/component/TimeBlockBar/TaggedNotes/TaggedNoteItem/TaggedNoteItem.tsx
  apps/client/src/page/archiving/index/component/TimeBlockBar/TaggedNotes/TaggedNotes.tsx
  apps/client/src/page/archiving/index/component/TimeBlockBar/TimeBlockBar.style.ts
  apps/client/src/page/archiving/index/component/TimeBlockBar/TimeBlockBar.tsx
  apps/client/src/page/archiving/index/component/TimeBlockBar/UploadedDocuments/FileItem/FileItem.style.ts
  apps/client/src/page/archiving/index/component/TimeBlockBar/UploadedDocuments/FileItem/FileItem.tsx
  apps/client/src/page/archiving/index/component/TimeBlockBar/UploadedDocuments/index.tsx
  apps/client/src/page/archiving/index/component/TimeBlockBar/UploadedDocumentss/FileItem/FileItem.tsx
  apps/client/src/page/archiving/index/component/TimeLine/TimeBlock/TimeBlock.tsx
  apps/client/src/page/archiving/index/type/blockType.ts
  apps/client/src/shared/component/TimeBlockDrawer/TimeBlockDrawer.style.ts
  apps/client/src/shared/component/TimeBlockDrawer/TimeBlockDrawer.tsx
  apps/client/src/shared/constant/index.ts
  apps/client/src/shared/constant/path.ts
  apps/client/src/shared/hook/common/useTimeBlockUploadFlow.tsx
  apps/client/src/shared/store/drawer.ts
  apps/client/src/shared/store/modal.tsx
  packages/ui/src/DatePicker/Trigger/DatePickerTrigger.style.ts
  packages/ui/src/DatePicker/Trigger/DatePickerTrigger.tsx
Labels: ✨Feature, 🍭규홍

#479 [Fix] 타임라인 QA 해결
  apps/client/src/page/archiving/index/ArchivingPage.style.ts
  apps/client/src/page/archiving/index/component/TimeLine/TimeLineHeader/TimeLineHeader.style.ts
  apps/client/src/page/archiving/index/component/TimeLine/TimeLineHeader/TimeLineHeader.tsx
Labels: 🫧다은, 🐛Bug

#477 [Feat] 워크스페이스 설정 페이지 qa
  apps/client/src/page/workspaceSetting/component/InfoSetting.tsx
  apps/client/src/page/workspaceSetting/component/ProfileSetting.tsx
  apps/client/src/page/workspaceSetting/component/TeamProfileSetting.tsx
  apps/client/src/page/workspaceSetting/component/WorkspaceDataSubmitButton/WorkspaceDataSubmitButton.style.ts
  apps/client/src/page/workspaceSetting/component/WorkspaceDataSubmitButton/WorkspaceDataSubmitButton.tsx
  apps/client/src/page/workspaceSetting/component/WorkspaceDelete.tsx
  apps/client/src/page/workspaceSetting/constant/index.ts
  apps/client/src/page/workspaceSetting/hook/useWorkspaceData.ts
  apps/client/src/page/workspaceSetting/index.tsx
  apps/client/src/page/workspaceSetting/queries.ts
  apps/client/src/page/workspaceSetting/styles.ts
  apps/client/src/page/workspaceSetting/util/index.ts
  apps/client/src/shared/component/LeaveModal/LeaveModal.tsx
  apps/client/src/shared/component/Modal/Footer/ModalFooter.tsx
  apps/client/src/shared/component/Modal/ModalFunnel.tsx
  apps/client/src/shared/component/SideNavBar/TeamList.tsx
  apps/client/src/shared/component/SideNavBar/index.style.ts
  apps/client/src/shared/constant/form.ts
  apps/client/src/shared/store/modal.tsx
  packages/ui/src/CommandButton/CommandButton.style.ts
Labels: ✨Feature, 🍭규홍

#485 [Refactor] 약관동의/회원가입 디자인 QA
  apps/client/src/page/signUp/index/component/TermItem/TermItem.style.ts
  apps/client/src/page/signUp/index/component/TermItem/TermItem.tsx
  apps/client/src/page/signUp/index/component/TermsAgreeButton/TermsAgreeButton.style.ts
  apps/client/src/page/signUp/info/InfoFormPage.style.ts
  apps/client/src/page/signUp/info/InfoFormPage.tsx
  apps/client/src/page/signUp/info/UnivFormPage.tsx
  apps/client/src/page/signUp/info/hook/common/useInfoForm.ts
  apps/client/src/shared/api/client.ts
  apps/client/src/shared/api/signup/info/type.ts
  apps/client/src/shared/constant/form.ts
  packages/ui/src/Select/Select.style.ts
  packages/utils/src/hooks/useTimer.ts
Labels: ⭐️주용, ♻️Refactor

#482 [Feat] 초대페이지 로직 수정 QA_2
  apps/client/src/page/dashboard/DashboardPage.tsx
  apps/client/src/page/dashboard/component/ItemAdder/ItemAdder.styles.ts
  apps/client/src/page/invite/constant/index.ts
  apps/client/src/page/invite/hook/common/useInvitationInfo.ts
  apps/client/src/page/invite/index.styles.ts
  apps/client/src/page/invite/index.tsx
  apps/client/src/page/onboarding/index.tsx
  apps/client/src/page/workspaceSetting/component/WorkspaceDelete.tsx
  apps/client/src/shared/api/middleware.ts
Labels: ✨Feature, 🤍보운

#483 [Refactor] 로그인 페이지 디자인 QA
  apps/client/src/page/login/index/LoginPage.style.ts
  apps/client/src/page/login/index/LoginPage.tsx
  apps/client/src/page/login/index/hook/useLoginMutation.ts
Labels: ⭐️주용, ♻️Refactor

#466 [Refactor] 401시 리프레시 토큰을 통한 재발급 인터셉터/미들웨어 수정
  apps/client/src/mock/handler/index.ts
  apps/client/src/page/login/index/hook/useLoginMutation.ts
  apps/client/src/page/signUp/index/TermPage.tsx
  apps/client/src/page/signUp/index/component/TermItem/TermItem.style.ts
  apps/client/src/page/signUp/index/component/TermItem/TermItem.tsx
  apps/client/src/shared/__generated__/schema.d.ts
  apps/client/src/shared/api/instance.ts
  apps/client/src/shared/api/interceptor.ts
  apps/client/src/shared/api/middleware.ts
  apps/client/src/shared/constant/api.ts
  packages/ui/src/DatePicker/Trigger/DatePickerTrigger.tsx
  packages/ui/src/DatePicker/index.style.ts
  packages/ui/src/DatePicker/index.tsx
Labels: ⭐️주용, ♻️Refactor

#490 [Refactor] Lottie react 버전 픽스
  package.json
  pnpm-lock.yaml
Labels: ⭐️주용, 🐛Bug
